### ISSUE TITLE
Have a few different language bundles as options for collaboration team configuration

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1087]
When settings up a collaboration team, currenly we allow selecting All, or specifying them individually.

Since unisubs has support for a large number of somewhat obscure, we should allow users to choose:

- All amara-supported languages
- ISO 639-1 languages only

If you chose the iso 639-1 option, then you can manually add to the language list by choosing them in the language chooser.

**Comment by bendk** [comment]
I'm not sure what "ISO 639-1" languages means exactly, but I do think it would be nice to have pre-built language bundles to choose from.

I'm going to remove this from the on-demand collaboration teams milestone, since I think we're done with this in our planning.

**Comment by PCF-Testing** [comment]
@bendk: @deanjansen: is this really in high demand in the real world? Given the cost of translating multiple videos into each additional languages, I seriously doubt clients would order languages in "bundles" - typically, videos get translated into 1-10 hand-picked languages.

The real issue is though that we could use a better language pick tool for new team settings UI. Language settings fields in the old task-based teams are way more user-friendly than what we have now in the new team UI.

**Comment by bendk** [comment]
I think this is more for enterprise teams that want their subtitles to focus on certain languages (aka the auto-create collaborations settings).  That said, I have no clue what the demand is.

**Comment by deanjansen** [comment]
I think we can probably table this one for the time being – better language selector takes some of the pressure off. 

I'm going to close this and we can re-open if we need to explore it later.
