### ISSUE TITLE
Editor hover menu is difficult to hover on

### ISSUE THREAD

**Issue by deanjansen** [pculture/unisubs#1740]
Currently the hover menu is to right and if your cursor falls at all out of alignment, it disappears.

Either one of these things would make it easier (no need to do both):
*Use a bit of js to make it stay open for a few ms (maybe 50?) so if your cursor leaves the menu it doesn't disappear
*Place the menu below and centered, so that your cursor has a much wider path to move on

![screen shot 2014-09-25 at 10 33 41 pm](https://cloud.githubusercontent.com/assets/216145/4415167/e2a53222-4525-11e4-946c-722de36a5ee4.png)

**Comment by jessehall3** [comment]
I added 2 pull requests that could both be used to address this issue.

#2578 turns the tool icon into a button that can toggle the toolbox menu on and off.

#2575 adds an invisible 45px margin to the left of the toolbox menu so that you no longer have to walk a tight-rope with your cursor just to get to the toolbox menu. I set up the margin to be as long (height-wise) as the toolbox menu, which might provide too much invisible hover space, but this can obviously be whittled down to your liking.

**Comment by PCF-Testing** [comment]
Of the two proposed solutions, I like #2575 better.

Reasons:

1) Toggle button is a less ergonomic solution because it needs to be clicked twice - before the menu action(s) and after, to hide the menu. It seems to be a bit of an overkill for this particular menu, but we may want to use this solution in the future for other controls in the editor, e.g. to hide/display formatting toolbar, search and replace toolbar, etc.

2) Styling of the toggle button - in ON state, it is yellow (fbf99e), which is different from other controls in the editor (which are in red, teal, or navy colors). In Chrome, after toggling off, the button leaves a trace to the right:

![wrenchbuttontoggledoff](https://cloud.githubusercontent.com/assets/288455/16485065/984e7ca0-3e71-11e6-8e82-77201c730b0a.png)

This said, I would vote for merging #2575, which just makes the menu comfortable to navigate without making significant changes in it.

**Comment by jessehall3** [comment]
Not disagreeing with any of Margarita's points, I just wanted to point out
2 things:

1) Style features like colors are the easiest things to change. I made the
active button yellow because I didn't know what to use and I wanted to be
sure you all would clearly see a color change.

2) Both those solutions can be used at the same time. That said, I do see
how the toggle feature could be overkill.

**Comment by bendk** [comment]
I typically prefer the click-to-toggle method, but in this case I'm thinking we should wait to make the change.  The issue with the focus ring on the right seems particularly annoying to me.  Let's try the other change only and see what the response is.  If it still feels like a bad experience to users, then we can investigate this one more.

**Comment by jessehall3** [comment]
Update --  I removed the focus ring in this pull request: https://github.com/pculture/unisubs/pull/2599

**Comment by PCF-Testing** [comment]
In gh-2599, it looks much, much better than before.

My only concern is that some users may have trouble figuring out how to remove the drop-down menu from screen (it only goes away after the button is clicked again). I was thinking of a hint instructing to click again to remove the menu, but didn't find a good place for it. Could it be done so that the menu is hidden and the button toggled off when a user clicks on a text input field - subtitle cell or note input?

**Comment by jessehall3** [comment]
I think I should be able to make those adjustments for automatically
toggling off the menu. Let me look into it, and I'll get back to you.

**Comment by bendk** [comment]
I think any click outside of the menu should hide it.

Also, maybe a visual cue that links the button to the menu would help users understand that the button controls the toggle.  It's a pretty standard UI, so I think a subtle hint would be fine.

**Comment by jessehall3** [comment]
I need clarification on the visual cue. Could you paste a screen shot of
something similar?

**Comment by bendk** [comment]
Maybe skip that part for now, that was more of an idea than a concrete suggestion.

**Comment by jessehall3** [comment]
ok

**Comment by PCF-Testing** [comment]
Deployed.
