### ISSUE TITLE
Redirect www.universalsubtitles.org/*/auth/create/ to www.amara.org/*/auth/create/

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#1929]
Some folks are still trying to create accounts through the older URL, which I'd expect to cause some trouble with cookies, third-party logins, etc., if it works at all.

**Comment by bendk** [comment]
The redirector script is almost what we need, there's just one tweak to it that I'd like to see and I opened up a PR for that.  I think we can accomplish this with the following:

  - Get Evan to accept this PR https://github.com/ehazlett/redirector/pull/1 or create our own docker image that uses it
  - Update deploy.py to remove universalsubtitles.org from alias_domains for our app containers
  - Start a docker container on DOCKER_HOST_1 (or 2) that runs the redirect script.  Something like:
     `docker run -P -h universalsubtitles.org -e INTERLOCK_DATA={"alias_domains": ["other", "domains"]} ehazlett/redirector -url=http://www.amara.org{path}` -code=301
  - Redeploy
  - Update the restart_routers jenkins command so that it also restarts the redirector containers
  - Document everything

**Comment by bendk** [comment]
I just implemented all of this.  There is a slight issue: if I go to `www.universalsubtitles.org/en/`, then I'm redirected to `www.amara.org/en` (no trailing slash).  This results in a 404 page.

I opened up ehazlett/redirector#2 for that.
