### ISSUE TITLE
Add the due dates to the current collaborations report

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1949]
Add in the due date of the job to this table: http://amara.org/en/reports/current-collaborations/.  Should help admins check if anything is falling behind.

**Comment by bendk** [comment]
Should be implemented on the gh-1949 branch.  Is that report getting too cluttered width wise?  Not sure what we can do about it, maybe add line breaks in some places, like between the date and time.

**Comment by bendk** [comment]
That branch is on amara-enterprise btw.

**Comment by jdragojevic** [comment]
@bendk: Could we show it as x days or minutes like we do in the collaborations table?

**Comment by bendk** [comment]
I'm not sure I like that change since reports are meant to last long.  For one there would be the issue of caching the result.  That's not too hard to fix, but it would mean some dev work.

The bigger issue is if you download CSV.  At that point, saying that something is due in "2 days" doesn't make so much sense.

**Comment by jdragojevic** [comment]
ok then let's leave it

**Comment by jdragojevic** [comment]
this was completed and deployed.
