### ISSUE TITLE
Place information on change percentage on diffing page

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1973]
On the diffing page, display the amount of change between the later and the earlier revision:
Text change - XX %
Time change - YY %

Request: http://ted-support.amara.org/helpdesk/tickets/77576
Reason: estimate the contribution made by a specific collaborator; evaluate the amount of errors made in a translation.

**Comment by bendk** [comment]
We used to have this feature and then disabled it after talking to TED.  I honestly don't know how useful those numbers were since the algorithm to calculate them was quite crude.

So I think we need to figure out a couple things:
  * Are we totally sure that TED wants this one?
  * Should we use the old algorithm or a new one?

**Comment by jdragojevic** [comment]
the url is ted-support, but that's just from the accout used, I don't think this request actually came from TED.  I think there's probably a better way we can do this than the old way, but I wouldn't consider it a priority for now.

**Comment by bendk** [comment]
We're going to redo this page and display something, but it won't be percentages because there isn't a good way to map changes to percentages.
