### ISSUE TITLE
Update subtitle upload forms

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#1980]
Right now we have several subtitle upload forms and they are are very messy.  We should update them to work with our current code/systems.
- The task upload form isn't used anymore so we should remove the code
- The normal upload form has a input for complete/not complete that isn't so compatible new subtitle workflow system, which is based on actions.  I think we can do one of two things:
  - Remove that input and add 2 buttons "Publish" and "Save Draft", which correspond to the buttons in the editor.
  - Keep the current input and make complete -> "publish" and not-complete -> "save-draft"
- The form inside the subtitle editor should just use the API code directly (#1830)

**Comment by PCF-Testing** [comment]
Why not keep things simple and always upload subtitles as an incomplete / draft version, prompting users to check subtitles in the editor? Subtitle files edited offline are often full of formatting errors, so a post-upload check is almost always a necessity.

**Comment by jdragojevic** [comment]
We need to have it possible to indicate the state of the subtitle directly on upload outside of the editor (either via the form or api).  With some of the on-demand provider processes, we want them to be able to manually upload completed subtitles without the extra step of navigating into the editor.

I like the idea of having the buttons say either Publish or Save Draft since that has a much clearer meaning of the consequence of what they are doing, rather than marking whether or not it's complete.

**Comment by bendk** [comment]
The API is a separate issue.  I don't have plans to change that one
The in-editor form is also a separate issue #1830.
I believe the only thing we're talking abut is the upload form from the video page.

**Comment by bendk** [comment]
We're ditching these forms as we move to the futureui code.  So let's close this one.
