### ISSUE TITLE
Billing record not created for subs uploaded via the editor

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2047]
If a user opens the editor to create a new language (for a team video) and uploads a version of subtites, a billing record is not created.

We should create a record with the type=upload.

**Comment by syl22-00** [comment]
That is because the new subtitles are added through pipeline, and checking for new subtitle language is done as a task, so at the time it checks whether language is complete, it is not set as complete yet, hence no billing record

**Comment by syl22-00** [comment]
After discussion, branch gh-2047-alt implements another solution: each time a subtitle_language is saved, if marked complete, creates a billing record on the tip. Will not create duplicates. Not sure whether that really makes sense.

**Comment by darren-bridenbeck** [comment]
I've been doing some testing, and it looks like subs uploaded from the editor still aren't showing in crowd reports. The behavior is the same as before -- if a subtitle is uploaded and no changes are made in the editor, it won't show in crowd reports. Once a change is made in the editor, it will trigger billing activity for the date that the edit was made.

The expected behavior is that once a subtitle is uploaded it is logged in billing activity (if the team doesn't use tasks.) If the team is using tasks the billing activity should be logged once they are approved.

**Comment by jdragojevic** [comment]
Can you please describe how you are testing this?   For testing I:

1. Chose a video on a crowd team (open no tasks)
2. Clicked to add a new version
3. Uploaded a subtitles file
4. Hit Publish

Result:  A billing record was created.



On Sat, Apr 4, 2015 at 12:15 AM, darren-bridenbeck <notifications@github.com

**Comment by darren-bridenbeck** [comment]
I tested this using a team with tasks. For testing I:

1) Performed a transcribe task, uploaded subtitle, submitted task.
2) Performed Review task, made no changes, approved task.
3) performed approve task, made no changes, approved task.

Note that I was logged in as a team Owner, so I was able to perform all three tasks as the same user.

**Comment by jdragojevic** [comment]
Testing on staging:

I chose the TED team - since it's a classic tasks team and seleted a video
1. As myself - I performed the transcribe task by uploading subtitles.  
2. Impersonated darren.bridenbeck to perform the review / approve tasks.
3. Ran all 3 report types for the team

Result: http://staging.amara.org/en/admin/billing/  - both translators and pro-services report show the entry for the selected test video: Mining Africa's power: Vera Songwe at TEDxLagos

@darren-bridenbeck - can you please clarify which team / video / report you were using to check this?
