### ISSUE TITLE
amara editor doesn't use the primary url

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2089]
If you add a second url to a video, and make it primary.  The amara editor still uses the initial url.

Expected: editor should default to using the url set as primary.

**Comment by jdragojevic** [comment]
testing branch gh-2089, I updated the video's primary url, confirmed with api:

```
GET /api/videos/F7WalSExmNKc/urls/
HTTP 200 OK
Content-Type: application/json
Vary: Accept
Allow: GET, POST, HEAD, OPTIONS

[
    {
        "created": "2015-03-10T05:12:34", 
        "url": "http://qa.pculture.org/amara_tests/birds_subs.mp4", 
        "primary": true, 
        "original": false, 
        "id": 19, 
        "resource_uri": "http://unisubs.example.com:8000/api/videos/F7WalSExmNKc/urls/19/"
    }, 
    {
        "created": "2015-03-09T03:52:47", 
        "url": "http://www.youtube.com/watch?v=Xg1MjFBzu2s", 
        "primary": false, 
        "original": true, 
        "id": 8, 
        "resource_uri": "http://unisubs.example.com:8000/api/videos/F7WalSExmNKc/urls/8/"
    }
]
```

Checking when I open the editor I see:

```
...
 "title": "Drilling for Oil and Gas", 
        "primaryVideoURL": "http://qa.pculture.org/amara_tests/birds_subs.mp4", 
        "id": "F7WalSExmNKc", 
        "videoURLs": [
            "http://qa.pculture.org/amara_tests/birds_subs.mp4", 
            "http://www.youtube.com/watch?v=Xg1MjFBzu2s"
        ], 
        "metadata": {}
    }

```

However in player, it's still using the youtube url:

```
<div class="video-container" id="video">

<iframe frameborder="0" allowfullscreen="1" title="YouTube video player" width="100%" height="100%" 
src="https://www.youtube.com/embed/Xg1MjFBzu2s?

rel=0&amp;modestbranding=1&amp;iv_load_policy=3&amp;disablekb=1&amp;showinfo=0&amp;origin=http%3A%2F%2Funisubs.example.com%3A8000&amp;controls=0&amp;wmode=opaque&amp;html5=1&amp;enablejsapi=1" id="widget2"></iframe></div>

```

**Comment by bendk** [comment]
This is related to 2 popcorn issues:

* popcorn tries to use media wrappers first, then defaults to html5 video.  So we will only play the html5 video if we can't play the other URLs with a wrapper (youtube, vimeo, etc).
* Even if you add HTML5VideoWrapper to the list of wrappers, it always returns "maybe" from _canPlayUri.  This is because it never knows if it can actually play the URL or not.

I'd really like to avoid touching the popcorn code for this, so I think we have 2 options:
* Don't worry about the html5 video issue.  The code should work correctly for other video types
* Only send the primary video URL to popcorn.  If it can't play it, then too bad.  Note that this will maybe cause another HTML5 video issue, because to fully support all browsers, you need to specify multiple video types.  However, that might be an issue no matter what we do.

**Comment by jdragojevic** [comment]
This came about from a discussion with fran who was trying to update urls to fix issues with on-demand.  I think he was basically trying to update brightcove urls.

I think it's probably OK to not worry about the html5 issue for now.

**Comment by franontanaya** [comment]
Specifically, I was uploading a MP4 version of the original brightcove video and setting it as primary to workaround playback issues, but popcorn was still picking up the original instead. 

So as I understand it, the HTML5 fallback is outside the video URLs loop:

https://github.com/pculture/unisubs/blob/667bdbd45f132eaf1fef60a2ed38193bed217204/media/src/js/third-party/popcorn.js#L3197

and it will try first to find a non HTML5 wrapper suitable for any of the URLs (starting with the Primary), and only if none of the videoURLs has a popcorn wrapper, then it'll dump all URLs to a HTML5 player and let the browser figure out which one to play.

A fix would then be to check within the loop if the source is specifically a MP4 or WebM file. A complete fix would also require to ffprobe the video codecs to know for sure it contains H264+AAC.

**Comment by franontanaya** [comment]
The reasoning was:

```
// We leave HTMLVideoElement and HTMLAudioElement wrappers out
// of the mix, since we'll default to HTML5 video if nothing
// else works.
```

If those wrappers actually checked at least for the file extension, the fix would be to add those back at the end of the wrappers list, because MP4 and audio files can be legitimate primaries, not only last resort fallbacks.

**Comment by bendk** [comment]
I believe the issue is still browser compatibility.  I believe it's still the case that certain browsers can only play certain video formats.  So we can check the file extension, but that doesn't mean we know the browser can play it.  So this seems similar to my second proposed solution.  We can force a particular video URL to be used, but then we will get in trouble if a browser can't play it.

So what about this logic: if the primary video URL is an HTML5 video, then we only send HTML5 video URLs to popcorn.  Hopefully that will make popcorn put together a video element with multiple sources (I'm not sure about this one though).

**Comment by bendk** [comment]
Okay, I just implemented the above logic.  It seems to be working well enough for me.

**Comment by jdragojevic** [comment]
looks good to me. @franontanaya is you'd like to try it on a demo branch - I made one here: http://gh-2089.amara.org/en/

**Comment by franontanaya** [comment]
Ok -- tested with Brightcove link first, MP4 added second, all four combinations of Original / Primary settings worked as expected; then set MP4 first, added the Brightcove link afterwards, same behavior. Chucked in a YouTube video and tried a couple settings, all still good. Thanks!
