### ISSUE TITLE
transifex cron job fails

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2090]
Get these messages regularly

Sun Mar  1 06:00:01 UTC 2015
fatal: Not possible to fast-forward, aborting.
git pull returned 128, retrying...
fatal: Not possible to fast-forward, aborting.
git pull returned 128, retrying...
fatal: Not possible to fast-forward, aborting.
git pull returned 128, retrying...
fatal: Not possible to fast-forward, aborting.
git pull returned 128, retrying...
fatal: Not possible to fast-forward, aborting.
git pull returned 128, retrying...
unable to git pull

**Comment by bendk** [comment]
This was happening on an old server that we have stopped.  I notice the emails stopped since friday.  The next step is to re-implement this.

**Comment by PCF-Testing** [comment]
@bendk: https://github.com/pculture/unisubs/tree/staging/locale has not been updated since Mar 13

**Comment by bendk** [comment]
Yeah, this is currently not working at all and we need to make a new build process to fix this one.  It's actually not so easy though and will probably take a me a day or two to do.  I think that we won't have time for this one for a while.

**Comment by PCF-Testing** [comment]
Just a reminder that translation updates have not been pulled in for a year.

**Comment by bendk** [comment]
This is fixed in the `translation-fix` branch.  I just pulled in new translations from the web.  I guess the way to test would be to see if they appear in that branch, but I'm not sure how to check what strings are new.

The new method doesn't use a cron job, it's a dev command that you can run manually.  I think there's advantages and disadvantages to both ways, but the manual way was simpler to implement.  If someone wants to run the command you need to set some things up, both on your local box and in the transifex settings.  I can help if you want to be able to sync translations.

**Comment by bendk** [comment]
You need to add your username and password to .transifexrc.

**Comment by PCF-Testing** [comment]
@bendk: Both are included there. Here, for security reasons, they have been replaced with placeholders in angular brackets, but GitHb has got those hidden.

**Comment by PCF-Testing** [comment]
Looks great.

**Comment by PCF-Testing** [comment]
Deployed.
