### ISSUE TITLE
Place link to the full list of available tasks at the bottom of team dashboard

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2111]
Place link "Click here to view all the available tasks in your language(s)" at the bottom of team dashboard

Requested in http://ted-support.amara.org/helpdesk/tickets/78279

Reason: for popular languages (such as Spanish) there may be no available tasks left in TEDTalks project, so the user with this language in settings will see an empty team dashboard. Meanwhile, other projects may have plenty of available tasks in this language. The link to the full list of available tasks should be always displayed to ensure that the dashboard is never empty.

**Comment by jdragojevic** [comment]
Currently there's a link in that same spot to see all the videos, and we are already displaying the link to the full list of tasks in the member tools section:

![image](https://cloud.githubusercontent.com/assets/299270/6637781/d0a6a06e-c97e-11e4-95d7-8277bd18909d.png)

Also - the dash will still be empty in the case of TED because the are only showing TEDTalks.

**Comment by PCF-Testing** [comment]
Actually, this goes about covering up the empty dashboard that looks like this:

![emptydashboard](https://cloud.githubusercontent.com/assets/288455/6637883/ef4d4e9c-c93c-11e4-9df9-a2b4fd28ab08.png)

The side panel is less visible, so inexperienced users can simply not notice a link placed there.

The original request was to lift the restriction that only TEDtalks tasks should appear in the dashboard, but adding a link should be an easier and cleaner fix.

**Comment by kslottow** [comment]
Issue moved to [pculture/amara-enterprise #1185](https://github.com/pculture/amara-enterprise/issues/1185) via [**ZenHub**](https://www.zenhub.com/)
