### ISSUE TITLE
Amara player displays subtitles with a delay

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2112]
This was reported by two users who, after painstakingly fine-tuning synchronization in the subtitle track, found that Amara player displays subtitles with a delay.

This can be observed on the following example:
https://www.youtube.com/watch?v=hp-TTzkkgWg - the subtitles are burnt into the video itself and uploaded to YouTube. YouTube subtitles are well synchronized with the burnt-in copy.
http://www.amara.org/en/videos/vTSi3JK0h6bO/info/chicksdressedaschickswithsubtitles/ - the same video on Amara. Overlayed Amara subtitles come with a ~ 0.1-0.2 s delay compared to burnt-in and YouTube copies. It seems that the delay is a bit more pronounced on slower computers.

These subtitles were made with the use of Amara editor, so it seems that the issue only affects the embedded player.

Related tickets:
http://support.amara.org/helpdesk/tickets/77646
http://support.amara.org/helpdesk/tickets/77622 (http://amara.org/nb/videos/O8ib0exve4b2/info/la-colere-aveugle/, subtitles were carefully synced locally with the use of Aegisub)

**Comment by bendk** [comment]
@syl22-00 would you want to look into this one?  I'm pretty sure this is similar to an issue we had with the subtitle editor.  For that, we would start video playback and subtitles at the same time, but with different timers and various factors would make them get out of sync.  The solution there was to watch for updates to the playback time and use that to sync the subs, instead of using some other clock.

**Comment by syl22-00** [comment]
@bendk actually the embedder uses our amarasubtitle popcorn plug-in that displays subtitles according to the `timeupdate` event fired by the video player. The issue is that it is not fired frequently, sometimes with 0.2-0.7 sec delay. Sometimes it fires a few times at the same time stamp. So with this delay between events, that's how we get subtitles that are displayed sometimes a fraction of seconds too late.

If this is a problem (is it?), a solution might be to do the opposite, which is to indeed use a timer with a higher frequency.

Or, possibly, the `timeupdate` event fires at intervals that depend on the workload, in which case what we need to do is improve performance of the embedder. I am looking at this now.

@PCF-Testing is it really an issue to have this delay?

**Comment by bendk** [comment]
Now I'm remembering this.  I think the easiest way is to set a recurring timer to fire ever 0.1 seconds or so.  Then call player.currentTime().  I believe that value changes more often than timeupdate events fire.  There may be a flag you have to set to make that happen.  I'm not sure about this one though.

The other option is a combination of a timer + timeupdate.  Something like this:
* When you start playback, set ``start_time = Date.now()`` and start a recurring timer ever 0.1 seconds.
* When the timer fires, you update the subtitles to ``Date.now() - start_time``
* When a timeupdate event fires, you recalibrate start_time to ``Date.now() - popcorn.currentTime()``

I think you also would need to convert Date.now() to milliseconds or something.  I'm not sure what the type of the return value is.

**Comment by PCF-Testing** [comment]
@syl22-00: while most users seem to be happy with what we already have now, more proficient subtitle makers have higher expectations for subtitle synchronization. If we could comply, that might earn more trust and vocal support for Amara, so, if technically possible, I think it is worth doing.

**Comment by syl22-00** [comment]
This should now be better in branch gh-2112. I switched the plugin to use the `frame` event rather than `timeupdate` event, as it is updated much more frequently.

@bendk the timer way of doing it, like in the editor, was less practical here as the embedder uses popcorn's subtitle capability, unlike the editor. That is the plugin receives the subtitle content in events fired by popcorn. So this fix is much simpler, and actually maybe working even better as the frame event is very frequent, with less than 0.1sec interval.

**Comment by PCF-Testing** [comment]
@syl22-00 : You can see the delay on http://gh-2112.amara.org/en/videos/PVUqbZzXis6e/info/chicksdressedaschickswithsubtitles/ if you increase the font size of YT subtitles and make them in a contrast color - but inside the editor both sets appear at the same time.

**Comment by jdragojevic** [comment]
I think the delay is significantly less obvious now than before the changes.  Given that this is a pretty uncommon case, I think we should take the improvements.

**Comment by jdragojevic** [comment]
Made pull request for this one.  The changes implmented do make a big improvement and @syl22-00 says that to get any further improvements we'd have to have to change susbtitles from a plugin to using something outside of popcorn as we do in the editor.
