### ISSUE TITLE
Mismatch between codes for Zulu and Malgasy in the task filter vs. manual tasks

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#2113]
The task filter in task teams posts "zul" and "mlg" as language codes, but "zu" and "mg" were expected.

This was seen on tasks that were created manually through the admin -- the issue may be either the filter list or the admin task creator.

**Comment by bendk** [comment]
This happens because certain teams want to use different language codes than our internal ones.  On the team's page, we use the language codes the team's codes.  On the admin, I'm guessing we use our own.

I don't really like the system (see #1813), but it seems to be working okay at this point.  Is there a specific issue that you need to work around?

**Comment by franontanaya** [comment]
Ok, so this is a non-issue. We uploaded these tracks via API and I used the long form codes for those two languages. 

If anything the language filter could show tasks for both synonyms, but since our focus is on the Collaboration model it may not be worth it. As of now it only matters for the tiny subset of users that may look up tasks in those two languages in that single team.

**Comment by franontanaya** [comment]
On a second inspection --

Both the Video has language filter and the Task language filters are using "zul" for Zulu, but only the video filter returns results, while the tasks filter shows the results posting "zu" instead. So it may be inconsistent.

**Comment by jdragojevic** [comment]
If you look at the list of language codes, you can see that we have both codes for zulu (zu, zul) and malagasy (mg and mlg)

https://gist.github.com/jdragojevic/d57be4a04d826bd6dddf
