### ISSUE TITLE
Display on diffing page how subtitle has changed - text, time, or both

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2117]
Requested in http://ted-support.amara.org/helpdesk/tickets/78458.

At present, changed lines are highlighted in red, but without downloading and comparing subtitle files it is hard to tell what exactly has changed - text, timing, or both. It would be way easier if we placed a text icon where textual changes have been made and a clock icon where timing was changed.

This might look, for example, as follows (but the exact position of the icons could be different - if it is easier design-wise, they may go into a separate column):

![diffingpagewithicons](https://cloud.githubusercontent.com/assets/288455/6700811/c9703044-ccd0-11e4-9e58-7ccead4cf61a.png)

IMO, icons would works better than changing the text color of the subtitle - friendlier to users with color vision problems and less dependent on the monitor calibration. I used glyphicons_all/glyphicons/png/glyphicons_054_clock.png and glyphicons_all/glyphicons/png/glyphicons_107_text_resize.png from assets for the above image.

**Comment by bendk** [comment]
This is implemented.  I'm not 100% sure about which icons to use, but I like the feature in any case.  Any suggestions for other icons?

**Comment by jdragojevic** [comment]
Icons are looking a bit large and dark.  If we could make them smaller (maybe 70% the current size) and lighter grey it would be better.

![image](https://cloud.githubusercontent.com/assets/299270/6747570/808e04fc-cedb-11e4-9991-b420b5288e21.png)

Also - what about trying this txt icon in place of the T for text:

![image](https://cloud.githubusercontent.com/assets/299270/6747583/9f72c7c2-cedb-11e4-9a3e-ec42452887d5.png)


filetypes-txt

**Comment by jdragojevic** [comment]
So I'm think we'd have something more like this: 

![image](https://cloud.githubusercontent.com/assets/299270/6748286/62a65ecc-cee4-11e4-88da-e8e8e682e99e.png)

**Comment by bendk** [comment]
100% agree with lighter and smaller.  Do glyphicons support getting smaller though?  I'm a little worried they will get blurry, which looks like it happened with your screenshot.

I'm also not sold on the txt filetype icon, just because that icon is so strongly associated in my mind with an actual file.  What about just a big "T" with a solid outline?

**Comment by syl22-00** [comment]
@bendk for the glyphicons, in the editor, I usually resized and greyed them using imagemagic's convert. I can do it for those too.

**Comment by jdragojevic** [comment]
a big T suggestion is fine.

re: the icons, isn't there a way to use them as an actual font so they can just be styled with css?

**Comment by bendk** [comment]
So I couldn't find a good way to resize that icon.  Is it possible that it's just hard to draw a sharp circle with less than 20px or so?  I notice that that icon is not listed in the halflings section for glyphicons.

I believe there is a way to get them as a font, but we would have to buy the pro option.  Personally, I like font awesome and it's free to use.  It also has a decent clock icon.

But for this one, maybe we can go a different way.  I just pushed a change that accomplishes this in a different way.  Instead of icons, we change the text color to red for text changes and draw a red dashed border around the time badges for time changes.

**Comment by jdragojevic** [comment]
I think this change looks OK - only red text when there is a text change is a nice visual.  We can revisit using icons when we manage to start using font-awesome, which I think we should do for the collab team ui changes.
