### ISSUE TITLE
Update amara embedder to use new api code

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2148]
API calls used by the embedder should be updated to  use the new api code.

should just be a matter of changing the urls.

**Comment by syl22-00** [comment]
This should now be done, in branch gh-2148. It includes changes from branch gh-2160 (#2160) to get the correct CORS headers.
It includes changes so that anonymous user can get read-only data from API.

**Comment by syl22-00** [comment]
This seems to be working now. One needs to make sure that:
* embedder can be loaded cross-domain (for instance if tested on a page with URL such as http://localhost:8000/..., it should also load succesfully with http://unisubs.example.com:8000/...)
* embedder can be loaded if no amara user is connected (need to make sure there is no user that is automatically connected because of a cookie).

**Comment by jdragojevic** [comment]
checked the various scenarios for the embedder with tasks, collabs, private and public videos.  All seems fine  to me.
