### ISSUE TITLE
After deleting subtitle cell, move focus to next cell

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2179]
After deleting a subtitle with ALT+BackSpace (or ALT+Delete), the focus should go to the next cell if one exists. If the deleted cell was the last in the set, the focus should go to the last remaining one, if possible.

Right now, in terms of convenience of deleting cells, we are worse off than before implementing the cell-specific context menu - since the deletion button went inside the collapsed menu, more mouse moves are needed to delete multiple cells. Adjusting the focus will at least simplify the process with the use of the keyboard shortcuts.

**Comment by jessehall3** [comment]
#2577 will open an adjacent cell after deleting a cell using a key-combo. Multiple cells can be deleted in a row using only the keyboard.

Even with this fix, I still had a hard time deleting multiple cells in a row. This was because if I failed to release the "alt" key quickly it would trigger some other OS-related hotkey function and take the focus off of the browser. This could be remedied by using a different key-combo, but with consistency in mind, that may not be an option.

Also to note, I left the functionality of the context menu alone. Deleting a cell using that menu will not trigger an adjacent cell to open afterwards.

**Comment by PCF-Testing** [comment]
The fix looks and feels wonderful, it does make a great improvement in the editor UX.

A bunch of unit tests related to collaborations break on the branch - probably because the private repo is newer than the branch.

Marking as waiting for deploy.

**Comment by jessehall3** [comment]
Thanks for the feedback. I'm going to have to figure out the issues with
the unit tests and get back in you. When i submitted the pull request, all
the tests were passing on my machine. I won't have time to work on this
today, but I'll get on touch with Ben to figure this out.

**Comment by bendk** [comment]
Don't worry about the tests.  Maggie was pointing out that this branch was written a while ago, so some of the tests are now outdated.

This issue happens alot because we have 2 repositories, a public one and a private one.  On the branch, the code in the private repo has moved forward, but the tests in the public have not.  Usually a merge fixes the issue.

**Comment by jessehall3** [comment]
Thanks for clearing this up.

**Comment by PCF-Testing** [comment]
Deployed.
