### ISSUE TITLE
Subtitles synced to YouTube have [br] tags in them

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2188]
Some of TEDx subtitles synced to YouTube have [br] tags instead of line breaks.

Example:
https://www.youtube.com/watch?v=IvBGUiJigf0 (Spanish)
https://www.youtube.com/watch?v=Wbd7urS-MwE (English)
https://www.youtube.com/watch?v=N-l1xtCMnpw (Dutch)
https://www.youtube.com/watch?v=othM2dwi2bE (German)

Other recently approved and synced subtitles have proper line breaks in them:
https://www.youtube.com/watch?v=Fr26scqsIwk (PT-BR)
https://www.youtube.com/watch?v=a8eDwAR3ujU (English)
etc.

This problem could not be reproduced at will on selected videos (the resulting line breaks were quite normal) or fixed on the broken videos - uploading proper VTT files still produced [br] tags.

**Comment by bendk** [comment]
I think the key here is figuring out how to reproduce.  Can you explain this part?

> uploading proper VTT files still produced [br] tags.

Does this happen for all videos, or just example videos where the automatic sync created the tags instead of line breaks?

**Comment by PCF-Testing** [comment]
@bendk: no, the same VTT file (https://drive.google.com/file/d/0B7j578ppG4loalE1Q295SnZtYlE/view?usp=sharing) produced different results with the TEDx video where tags appeared after automatic syncing (subtitles uploaded by TED staff from the file also had tags) and with my own video, where both automatic syncing and uploading from VTT worked nicely.

TEDx video: https://www.youtube.com/watch?v=Wbd7urS-MwE (English has tags)
Control video: https://www.youtube.com/watch?v=KRdJRStzrws (English has proper line breaks)

No idea why some of TEDx videos behave in such weird way, while other videos from the same channel happily accept subtitles with line breaks and do not mutilate them.

**Comment by bendk** [comment]
When you say "uploading from VTT", do you mean directly uploading using youtube.com?

This may be related to the fact we're syncing to the ASR tracks.  If not, then it seems pretty out of our control.

**Comment by PCF-Testing** [comment]
> When you say "uploading from VTT", do you mean directly uploading using youtube.com?

Yes, I sent a file to TED staff and asked them to try and upload it through the video's CC settings - but it seemed to produce the same results as syncing by API.

**Comment by franontanaya** [comment]
The [br] tags are from the SBV format. The file linked is a proper VTT, but is it possible that somehow SBV files are being uploaded with a .vtt extension?

**Comment by bendk** [comment]
We actually upload as SBV, but I'm pretty sure that we set the content-type correctly so that youtube should interpret the data as SBV.

In any case, it seems like the results are varying pretty wildly both with our uploads and with manual uploads.  At this point I think it's simple a google issue.  Maybe we could use a different format to upload and that would improve things, but it seems like it's happening with both SBV and VTT so I don't have a huge amount of hope for that.

**Comment by bendk** [comment]
I've tried really hard to reproduce this one, but it's really tricky.  I think it may happen on certain videos, but not others.  If this is happening to you, can you help me debug it?  I would love the following info:

  * URL to the video on amara that the issue is happening on
  * Youtube URL for the same video
  * What happens if you download the subtitles as SBV, then manually upload it to youtube?  What about VTT?  DFXP?

**Comment by PCF-Testing** [comment]
We have received a tip from FD that manually uploading subtitles to YouTube in SRT format fixes the issue - subtitles get displayed with proper line breaks, without the offending tags.
For reference, manual upload of VTT subtitles does not help.

Related ticket:
http://ted-support.amara.org/helpdesk/tickets/79583
Video:
https://www.youtube.com/watch?v=rHl1YRwgvxs
http://www.amara.org/en/videos/Glj6Aivmh0g0/info/passionate-voices-episode-2-david-revoy/

Other examples of affected videos can be found in 
http://ted-support.amara.org/helpdesk/tickets/79402
http://ted-support.amara.org/helpdesk/tickets/79500
http://ted-support.amara.org/helpdesk/tickets/79247

http://www.youtube.com/watch?v=7j4ytsunao8
https://www.youtube.com/watch?v=0s2HhR8yXag
http://www.youtube.com/watch?v=JQ7boNzNNT0
https://www.youtube.com/watch?v=-NxoPqYwVwo
http://www.amara.org/pt/videos/mbQgIBhduicD/en/484044/

**Comment by jdragojevic** [comment]
About 2 years ago, we switched away from pushing .srt files and changed to sbv because there were issue with the formatting of html tags when displayed on youtube.

Please reference: https://github.com/pculture/unisubs/issues/529

@PCF-Testing: Can you please do some testing with .srt files and check if this is still an issue?  If not, then we could switch back to .srt.  Otherwise we'd have to choose which issue is worse for the users until youtube fixes one or the other.

**Comment by jdragojevic** [comment]
Did a quick test locally - it appears that with srt files, we'll still have an issue with the formatting on youtube.

![image](https://cloud.githubusercontent.com/assets/299270/8125123/249e556c-10e3-11e5-956c-034a5d5600e8.png)

**Comment by jdragojevic** [comment]
Looks like we can actually use dfxp with youtube now.

I tried changing the format output to dfxp and mime to text/xml and was able to get formatted subtitles on youtube.

You can see the **bold** text is displayed, and confirmed that & chars are correctly displayed.  I think possibly one thing we'd need to worry about is our dfxp header, since we preserve whatever we get in.  Don't know if someone could input dfxp to amara that would then have odd formatting consequences on youtube.  But at this point, it seems it could be the least worst thing.

![image](https://cloud.githubusercontent.com/assets/299270/8125726/a503974e-10e8-11e5-8e2b-19ca05f575c0.png)

```
 def _format_subs_for_youtube(subtitle_set):
-    return babelsubs.to(subtitle_set, 'sbv').encode('utf-8')
+    return babelsubs.to(subtitle_set, 'dfxp').encode('utf-8')
 
 def get_youtube_language_code(language_code):
     """Convert the language for a SubtitleVersion to a youtube code
@@ -78,10 +78,10 @@ def update_subtitles(video_id, access_token, subtitle_version):
     caption_id = find_existing_caption_id(access_token, video_id,
                                           language_code)
     if caption_id:
-        google.captions_update(access_token, caption_id, 'text/sbv', content)
+        google.captions_update(access_token, caption_id, 'text/xml', content)
     else:
         google.captions_insert(access_token, video_id, language_code,
-                               'text/sbv', content)
+                               'text/xml', content)

```

**Comment by bendk** [comment]
So I'd like to try to reproduce one really weird part of this one.  I took the subtitles form this video and downloaded the VTT:  http://www.amara.org/pt/videos/mbQgIBhduicD/en/484044/

I then manually uploaded them to a test video.  Linebreaks worked, there were no [br]s present.  Is there anyway we can try uploading the VTT to the youtube video?  Is it possible that this ticket depends on the video the subtitles are attached to?

**Comment by bendk** [comment]
I'm also happy to change it to DFXP if that helps the formatting issues.

**Comment by PCF-Testing** [comment]
@bendk: I tried to reproduce the issue in the same way as you did, with the same result. Looks like for some unknown reason the problem affects only some of the videos, so I guess the only way to reproduce this at will would be to have someone at TED to upload a VTT file to one of the troublesome videos.

**Comment by bendk** [comment]
So this is implemented in the gh-2188 branch.  I can't know for certain if it won't hurt other cases, but it seems like a reasonable idea to me.

@jdragojevic what do you think?

**Comment by jdragojevic** [comment]
Seems like each format has it's only special set of issues on youtube.  I have a bunch of videos I made and in some of the subtitles the text is positioned to far left when the dfxp is uploaded.  

![image](https://cloud.githubusercontent.com/assets/299270/8262881/4d43b842-16d6-11e5-8610-661fad730e33.png)

You can see the positioning is fine in the amara player, but shifted in the dfxp player.

**Comment by bendk** [comment]
Just pushed a change to that branch that tries VTT insead of DFXP.  Hopefully this one will be the least bad.

**Comment by jdragojevic** [comment]
vtt doesn't have the positioning issues.

**Comment by PCF-Testing** [comment]
Looks like this is not happening anymore, and resyncing the affected subtitles resolves the issue. Closing this one.
