### ISSUE TITLE
Display subtitles in time order on the subtitles page

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2199]
From #945: Right now we display subtitles in the order they appear in the DXFP.  This is usually in time order (sorted to the start times are ascending), but not always.  We should display in time order regardless of how things are ordered in the DFXP.

**Comment by PCF-Testing** [comment]
@bendk: actually, I think there is more to it than just correctly displaying on Amara pages - subtitles should also get downloaded (in all formats) and exported to other software systems (such as TED and YouTube) in proper order.

**Comment by bendk** [comment]
That's the tricky issue.  As far as I know, there's nothing in the DFXP format that specifies what order the item should be in the source.  I believe that any order is valid.  One of the goals of our DFXP handling is make as few changes to the source as possible.  So as much as I think it's strange and weird for the items to be not ordered by time, I don't feel like we should change it (at least without more discussion).

**Comment by jdragojevic** [comment]
Another possibility is that we could take the opposite approach and display the subtitles exactly in the order they are presented to us in the subtitle editor.  In that case the mis-ordered subs would get flagged as timing errors and the user would have to correct them in order to proceed.

But that would also be us enforcing order on something that is not technically incorrect.
