### ISSUE TITLE
Subtitles not locked when open for editing by some user

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2216]
Reported in http://ted-support.amara.org/helpdesk/tickets/79246, could reproduce on production.

Steps to reproduce:
1. Open some subtitles for editing as User 1, e.g. http://amara.org/en/subtitles/editor/eSe9MsMdhLnP/en/
2. In another browser, open the same subtitles as User 2.

Result: both users can open subtitles for concurrent editing.
Expected: if someone is editing subtitles, they should be locked for editing by anyone else.

**Comment by jdragojevic** [comment]
I'm getting the locked message, is there extra info to reproduce? 

![image](https://cloud.githubusercontent.com/assets/299270/7580452/c2dce58a-f875-11e4-9cf6-ce1c6dadec1b.png)

**Comment by PCF-Testing** [comment]
This seems to happen when users start editing the same subtitle set with a small difference in time.

**Comment by jdragojevic** [comment]
When you say small - about how many seconds.  And is this being reported by a real-world use or someone testing a concept.

**Comment by bendk** [comment]
Also, can you confirm it's a different browser, not a different window/tab in the same browser?

**Comment by franontanaya** [comment]
I believe this may still be an issue. We sporadically see duplicated Approvals with an assignment time up to 4 seconds apart.

This could possible be due to the editor lock taking a while to load, so when an available approval notification goes out folks may click it while the first one is still loading scripts.

https://github.com/pculture/unisubs/blob/186f893a5caa0a61ddc593668cc2409350227409/media/src/js/subtitle-editor/app.js

I don't know if this list sets the loading priority, but there's several sizeable scripts that may be running before lock.js.

https://github.com/pculture/unisubs/blob/8c00b53a34aa5e8f9b78317939b5672091750b77/settings.py

 If lock.js has no significant dependencies and side effects it should be running as high as possible.

**Comment by bendk** [comment]
There are two separate synchronization problems here.  Locking the editor so only one can access it is the first issue.  The other one is locking the approval task, so only one person can accept it.  I wonder if it's possible that the editor lock is working, but the task isn't getting locked.  

Do both users get into the editor at once?  Does it happen for collab teams?  Can you point to a subtitle set where this happened?
