### ISSUE TITLE
Video ID filter ignored in API Activity resource

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2238]
Reported in http://ted-support.amara.org/helpdesk/tickets/79474.

Example:
GET http://amara.org/api/activity/?video=yycZQT9E0Tt9&language=ja&team=ted&limit=20&format=json
returns activity for Japanese subtitles for all the videos, not just the desired one.

Expected:
the activities returned by the query must be filtered by the video ID.

**Comment by jdragojevic** [comment]
It appears that the issue comes in when the team parameter is added:  this query works fine:

http://amara.org/api/activity/?video=yycZQT9E0Tt9&language=ja

&format=json isn't necessary, and I'm not sure why the team filter would be appropriate if you are querying by video id.

**Comment by PCF-Testing** [comment]
Normally, when applying two filter criteria (as, for example in SELECT * WHERE (a IN x) AND (a IN y)), it is reasonable to expect a result set that would match both criteria, even if "IN x" automatically means "IN y".  If "team" filter parameter in API method makes "video" parameter ignored, it does not feel right and should at very least be clearly indicated in the API documentation.

**Comment by bendk** [comment]
I agree that it's confusing in this case.  I also think it's broken in general, since no filters returns video activity for the API request user, then adding a single GET param results in a totally different result set instead of filtering the original result set.

I think we need a more broad fix for this issue, see #2239.

For this one, I'll just make a change in the docs to indicate the current behavior.
