### ISSUE TITLE
URL from Kaltura RSS changes, resulting in videos being added multiple times to teams

### ISSUE THREAD

**Issue by darren-bridenbeck** [pculture/unisubs#2278]
Example:
Original version of a video: http://amara.org/en/videos/slUL9Efa4iEm/info/a-unique-artist/?tab=urls
Duplicate version added after URL changed in feed: http://amara.org/en/videos/zGkAG3sZbqjO/info/a-unique-artist/?tab=urls

RSS Feed: http://www.kaltura.com/api_v3/getFeed.php?partnerId=1487861&feedId=0_krqcltyk

Note if you can't see these URL's, try impersonating "darren.bridenbeck"

**Comment by kslottow** [comment]
@PCF-Testing can you check if this is still the case? Since a client wants to start using Kaltura

**Comment by PCF-Testing** [comment]
I am not sure why exactly this happened in the case described in this case - possibly, the feed was somehow modified on the Kaltura side, which has resulted in the change in the video URLs. However, I can confirm that the same video can be included into multiple Kaltura feeds with different URLs and imported to an Amara team multiple times. Since the video's URLs are different, from Amara's point of view these multiple instances are perceived as different videos. So it seems to be a peculiarity of Kaltura platform and not a problem on the Amara side. I think the ticket should be closed, since it is actually not a bug.

**Comment by kslottow** [comment]
thanks Maggie!
