### ISSUE TITLE
Amara URL (www) affects the embedder controls

### ISSUE THREAD

**Issue by deanjansen** [pculture/unisubs#2293]
Videos on a collab team are not showing the subtitle controls: http://amara.org/en/videos/P0V7TdetfKdA/info/kellymcgonigal-2013g-transcript/ unless you add a www in the address bar, http://www.amara.org/en/videos/P0V7TdetfKdA/info/kellymcgonigal-2013g-transcript/

![screen shot 2015-07-21 at 8 53 52 am](https://cloud.githubusercontent.com/assets/216145/8804544/fecbdd26-2f89-11e5-94c5-773c2d63d55f.png)

vs

![screen shot 2015-07-21 at 8 53 40 am](https://cloud.githubusercontent.com/assets/216145/8804559/0468bb8c-2f8a-11e5-8e1a-ee8d76b67178.png)

**Comment by bendk** [comment]
This is working for me with both URLs.  Can you double check?

**Comment by deanjansen** [comment]
I just made the team private again – if you impersonate user "dean" you should be able to see this happen.

**Comment by bendk** [comment]
I'm seeing it now.  This happens for a few reasons:

a) we always send the request to www.amara.org, even if the host is amara.org
b) we don't include "cookie" in `Access-Control-Allow-Headers`, so we don't send the cookie
c) without the cookie, we can't lookup the user's login info
d) since it's a private video, without the login info we don't return any subtitle data from the API

Maybe the simplest fix would be to always redirect to www.amara.org.  I think that would save a lot of other issues as well.  I think we should wait until ehazlett/redirector#2 is fixed though.

Another fix would be to add cookie to `Access-Control-Allow-Headers`.  Not sure about the security implications of this one though.

**Comment by deanjansen** [comment]
I can't remember this happening on other (non-collab) teams, but maybe I'm not remembering correctly.

If we do redirect all requests, maybe we could send them all to amara.org instead... it's cleaner, especially when people are sharing URL's in twitter or on other social media.

**Comment by deanjansen** [comment]
I verified that this affects both collab and non-collab teams, but depends on having the team marked as private.

**Comment by franontanaya** [comment]
This issue still affects the subtitle loading control. If the user isn't logged in to www.amara.org, loading subtitles for the videos in the main and language pages fail as the embedder sends the GET request to the API via www.

**Comment by bendk** [comment]
@syl22-00 do you have time to look into this one?

**Comment by syl22-00** [comment]
This can also be witnessed this way on dev environment:

1. Member of a team with private videos connected, using domain http://localhost:8000
1. No member of this teams connected using domain unisubs.example.com
1. Subtitles of videos from that team can not be loaded. As explained in previous commands, the GET command retrieves via a fix domain (in this case unisubs.example.com).

Solving it this way:
* Embeders within amara website: get domain from host page url
* Embedders outside amara website: document the possible issue in embedder doc, but very unlikely to be an issue in real life, probably nobody would rely on embedder for non-public videos.

**Comment by syl22-00** [comment]
this was fixed in branch gh-2293

**Comment by PCF-Testing** [comment]
Looks good to me.

**Comment by PCF-Testing** [comment]
Deployed.
