### ISSUE TITLE
Some usernames don't populate in "Invite Member" dialogue

### ISSUE THREAD

**Issue by darren-bridenbeck** [pculture/unisubs#2305]
This has happened occasionally with other usernames in unpredictable / reproducible ways, but hopefully the example below helps pinpoint this one!

Example:
When searching for the username "Agna" the username doesn't populate in the Invite Member drop-down (instead, only the username agnan.zakariya.soewardi displays):
![screen shot 2015-07-31 at 12 26 11 pm](https://cloud.githubusercontent.com/assets/5092242/9015701/8637a4d2-377f-11e5-82d5-9c495d29adbc.png)

When in fact this user actually is registered with Amara (see django screenshot):
![screen shot 2015-07-31 at 12 25 30 pm](https://cloud.githubusercontent.com/assets/5092242/9015707/945ef6b4-377f-11e5-8d86-719875680860.png)

**Comment by bendk** [comment]
I think what may be happening is too many results match the queryset and we're not promoting the exact match to the top oy the list.

**Comment by bendk** [comment]
Fixed this in the gh-379 branches since it was an issue for those inputs as well.  This affects the user field for the following forms:

* Invite team member
* Add project manager
* Add language manager
* Assign user to collaboration
* Add provider queue account

This should be fixed for all forms using the new styles (i.e. not the old-style team forms).

Please check the following:
* The autocomplete works in general
* If you search exactly matches a username, that user is listed first
* We don't return users that are invalid (For example trying to invite a user that is already a team member)
* The error messages make sense if you manually enter:
  * a username that doesn't exist
  * an invalid username

**Comment by bendk** [comment]
This got auto-closed, but we should wait until it's actually deployed to production.

**Comment by PCF-Testing** [comment]
Generally works on smaller data sets (team members) for the following forms:
* Add project manager
* Add language manager
* Assign user to collaboration
with the caveat that only usernames are honored as input - first/last names are not being checked for matches (this might be hard to implement, but it is very likely that the users would expect this behaviour).

With Invite Member, the behaviour is the opposite to described in the ticket - when trying to invite "agna", lookup does not return the result returned by old-style pick tool.

**Comment by PCF-Testing** [comment]
Deployed.
