### ISSUE TITLE
Changing the title of the original language does not change the title of the video

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2324]
Reported in http://ted-support.amara.org/helpdesk/tickets/80645.

Steps to reproduce:
1. Edit the original language of the video, modifying the title. Publish the modified version.
2. Check the video title on the main video page - it remains unchanged.

Reproduced on http://amara.org/en/videos/1ggCuF4pbdoz/

**Comment by bendk** [comment]
Pretty sure this happens when the title has been edited after its already published.  Tested on tasks, simple, and old-style public teams and the title changed when I published the first version, but not on subsequent versions.

**Comment by bendk** [comment]
Actually, I think it's a race condition.  It will happen sometimes and sometimes not, depending on luck.

**Comment by bendk** [comment]
So I believe the issue was a race condition between 2 pieces of code.  I made a quick change that I think should fix the issue for normal cases.

#2335 is a more complete/correct fix.

Not sure how to test this one well since it was only happening to me under certain circumstances.  I guess you should just do your best to reproduce it in the gh-2324 branch.

**Comment by PCF-Testing** [comment]
Does this branch include the fix to the issue? I keep reproducing the problem on the affected videos on production very consistently, but on gh-2324 this never happens for me.

**Comment by bendk** [comment]
It contains something that should fix it in most cases.   Judging by your report I think it's good enough to make a PR for.

**Comment by PCF-Testing** [comment]
Verified on staging.

**Comment by PCF-Testing** [comment]
Deployed.
