### ISSUE TITLE
Merge CollaborationLog and Action models

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2350]
CollaborationLog is how we track actions for a collaborations.  If possible it would be nice to merge this with the Action model to have 1 system.  The main issue is that CollaborationLog is part of amara-enterprise.  To implement this we would need some sort of extension system for Action where apps in optional repositories could add they own activity types.

**Comment by bendk** [comment]
One nice thing about this is it would enable collaboration activity to be listed in the team activity page.  I think that's a really good thing and would fix pculture/amara-enterprise#356

**Comment by bendk** [comment]
There are a bunch of permissions questions related to this.  Should collab activity be viewable by the public?  If you move a collab to a new team, does the new team see the collab activity from the old team?    Does the source team see the activity from the work team?  Evaluation teams just make this more complex.

A related question is if the activity should appear on the video page.

For my initial pass, I'm going to just make it so that collab activity is private to the team that's doing it.  At first it will only appear on the team activity section.  Once we switch over the new video/subtitles pages then we can also display it there, if the user is accessing the team version of the page.

I think this fits well with the AOD use case.  It might not work so well if we had a team like TED that was sharing work somehow.  However, there's a lot of tricky parts to it so I want to just stick with a simple initial implementation and we can make it more complex later.

**Comment by bendk** [comment]
One other tricky issue is moving a collaboration from team to team.  I made it so this generates 2 activity records.  On the old team, you'll see a record for the collab being moved from the team.  On the new team you'll see a record for the collab being moved to the team.  Both records mention the other team and the admin who performed the action.  Hope this isn't an issue with leaking information.

**Comment by bendk** [comment]
Another one is collab delete when there are multiple teams involved in the collab.  I made it so it generates an activity record on the work team and the source team.  I didn't try to make it create a record for the evaluation teams if they are set.  I don't think collabs should be delete once they reach that state.

**Comment by bendk** [comment]
Okay the initial implementation is done.  It's in the collab-activity branches on both unisubs and amara-enterprise.

The main things to test are:
  - Activity gets created correctly
  - It gets associated with the correct team
  - It looks okay in the activity listing (these pages should change soon, so minor issues should be okay here)

Here's a list of the different activity types.  Hopefully the name should be self-explanatory:
- ActivityTypeJoin,
- ActivityTypeLeave,
- ActivityTypeAssign,
- ActivityTypeReassign,
- ActivityTypeUnassign,
- ActivityTypeEndorse,
- ActivityTypeSendBack,
- ActivityTypeMarkComplete,
- ActivityTypeMoveFrom,
- ActivityTypeMoveTo,
- ActivityTypeDelete,
- ActivityTypeProviderAccept,
- ActivityTypeProviderSubmit,
- ActivityTypeProviderUnassign,

**Comment by PCF-Testing** [comment]
@bendk: did you see my comments on collab-activity branch I left on slack channel just before the weekend?

**Comment by bendk** [comment]
Yes I did, sorry for the slow response....

- We aren't going to migrate the old collaboration logs.  It's not trivial to do and, from what I understand, OD isn't currently using them, so we're not loosing anything.
- Yes this will add more activity to the team.  We should think about how to handle it.
  - Adding a before/after filter could be nice, but I'm struggling to see how it would help this issue.  If the activity listing has a bunch of activity that I'm don't care about, how would I know what dates to filter for?  Seems like pagination is just as good in this case.
  - Maybe we could take some activity types and only show them on the team video page (I'm thinking join, maybe endorse/sendback).
  - Maybe we could just not log some of the activity types
- I'm happy to change the wording on "accepted".  I used it because I thought that's what the official new term is, but I'm not sure if that's true or not.  We should try to create a document that captures the correct terms for everything.
- I think the exception you got was for the same issue as sylvain had on the dashboard branch.  I'm going to cherry-pick his fix to master to fix that.

**Comment by PCF-Testing** [comment]
* Activity is particularly important when we are investigating some incidents, disputes, or bugs - in these cases, we would be checking events within a specific time period around the incidents. Having "After" and "Before" filters will help avoid clicking through hundreds and hundreds of pages with other events. It might also help if the video history listed entries for joining, leaving, user reassignment/removal, endorsement, sendback, and marking as completed.

* The list of available activity types perhaps should match the team type. I don't think a task team will ever need the collab-related actions, they will only confuse users. A simple team will need neither task actions nor collab actions. The edge case I am not sure about is collab team - since we are going to convert task teams into collab teams at some point, they'll need a tool for viewing the past activities, so collab teams should probably keep the task actions

* In the activity type filter, we'll need to split "Collaboration endorsed" into "Endorsed by subtitler", "Endorsed by reviewer", "Endorsed by approver" for more detailed analysis. (It would be nice to keep the aggregate type as well.)
"Collaboration sent back" should be split into "Sent back by reviewer" and "Sent back by approver".
 
* On the branch, an exception happens on attempt to assign a user to a collaboration:
DatabaseError at /teams/collab-test/collaborations/
(1146, "Table 'amara.collab_assignmentrecord' doesn't exist")
Request Method:	POST
Request URL:	http://192.168.1.133:8000/en/teams/collab-test/collaborations/
Django Version:	1.4.21
Exception Type:	DatabaseError
Exception Value:	
(1146, "Table 'amara.collab_assignmentrecord' doesn't exist")
Exception Location:	/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py in defaulterrorhandler, line 36

A similar exception happens when a user is removed from a collab.

* Moving a collab to a different team is not logged properly - the entry only has the admin's username, no other data.

**Comment by bendk** [comment]
Bunch of good UI points there.  I made pculture/unisubs#2613 and pculture/unisubs#1614 for the first two.  I don't think 2613 should block merging this one, since right now there's no way to do anything with team collab activity.  I do think 2614 should block it, since makes the UX way worse for the non-collab teams.

It's not so easy to split up the activity types into different subtypes.  Are you sure this is a requirement?  Could we try it without the subtypes and see how difficult it is?

I forgot to make a migration.  I think that should fix the DB errors.

I think the move record should display properly now.

**Comment by PCF-Testing** [comment]
- Confirming that the migration has fixed collaboration reassignment issues.

- Links to videos in Collaboration Joined and Collaboration Left activity entries are still broken:

![brokenlinksinactivityrecords](https://cloud.githubusercontent.com/assets/288455/17269798/76389968-5607-11e6-8e7b-4d1ffce26dd5.png)

- Could the assignment role be displayed next to the username? I.e. instead of 
"User One endorsed the French subtitles for Waikiki Beach Walk (translater)"
display
"User One (translator) endorsed the French subtitles for Waikiki Beach Walk"

- "Translator" should spell with "o"

- The collaboration history on the collab details page will be sorely missed. Could it still be displayed there? Otherwise, there is no easy way to filter the activity log for the particular video and language.

- @deanjansen: could we please have a different phrase for Collaboration Joined activity? The current wording is "[username] accepted the [language] [role] assignment for [video]". The word "accepted" sounds really awkward here because it is strongly associated with passing the review stage of subtitle workflow. Could it be replaced with something more neutral, e.g. "[username] started working as [role] on [language]  for [video]"?

**Comment by deanjansen** [comment]
@PCF-Testing Your re-wording sounds great – @bendk seem OK to you? 

Note: For the new UI, the layout will change significantly and should eliminate this potential for confusion.

**Comment by bendk** [comment]
I fixed the joined/left message errors, "translator", and also put back the history on the details page.  I changed the joined message and also the left message to "starting/stopped working as [role]..."

We might be able to move the role for endorsments, but it's actually kind of awkward because of the way the code is set up.  Could we keep things like this for now, and reassess with the new UI?

**Comment by PCF-Testing** [comment]
On attempt to open editor as subtitler, got yhe following exceptio:

AttributeError at /subtitles/editor/EySXblJnTW2t/en/
'ActivityRecordNoteWrapper' object has no attribute 'get_username'
Request Method:	GET
Request URL:	http://unisubs.example.com:8000/en/subtitles/editor/EySXblJnTW2t/en/
Django Version:	1.4.21
Exception Type:	AttributeError
Exception Value:	
'ActivityRecordNoteWrapper' object has no attribute 'get_username'

**Comment by bendk** [comment]
That one should be fixed.

**Comment by PCF-Testing** [comment]
After the latest changes, the Notes area in the editor is jammed with collab history entries, with HTML tags and all. Meaningful notes can easily get lost in the noise; is there a way to filter out only "real" notes and display them in the editor?

![collabhistoryineditornotes](https://cloud.githubusercontent.com/assets/288455/17437190/24bae716-5ad1-11e6-93db-9a3ca4fc17fb.png)

**Comment by bendk** [comment]
I thought people liked the activity record in the editor.  I think one of the things we should improve is putting them in their own section, but for now what if we just made the tags work correctly so they don't take up so much space?

**Comment by PCF-Testing** [comment]
I think all these log entries in the editor notes are more of a distraction because in real life notes are used for collaborators and site personnel communicating between each other - leaving feedback on the quality of subtitles, posting instructions on how to translate specific words/acronyms, etc. Multiple activity entries, especially when a collab is bounced back and forth or an assignment is repetitively taken and dropped, can easily silence this useful information.

Also, we were planning to add the option for deleting unwanted editor notes, and activity entries definitely should not be deletable.

Copying in @deanjansen for opinion on this matter.

**Comment by bendk** [comment]
I completely agree with this.  I just remember it being a feature request.  I don't want to remove a feature without confirmation that it's not needed.

**Comment by deanjansen** [comment]
+1 on removing them. 

We may eventually decide there are a subset of activities that we may want to show (or a separate place for showing them), but I agree that mixing the two would be messy and distracting.

**Comment by bendk** [comment]
Okay, removed.

**Comment by PCF-Testing** [comment]
Well, this latest change put us back to square one because the collaboration actions are now gone not only in the editor, but from the collab details page as well. This leaves us without tools for troubleshooting /debugging issues when collabs do not behave as expected - normally the collaboration history on collab details page would be #1 thing to check.

In a perfect world, I'd like to see activity as follows:
- On team activity page: all activity related to team members, videos, subtitles, collaborations (or tasks), comments. This looks fine on the branch.
- On the video activity page: all activity related to the video, subtitles, comments, and the key activity on collaborations/tasks (endorsed, sent back, published). The collaboration-related activity is not present on the branch.
- On the user's personal activity page: all activity performed by the user. This works as expected on the branch.
- On the collaborations details page: all activity related to the collaboration, including notes made by collaborators and other team members, and collaboration actions (joined, left, assigned, endorsed, sent back, etc.). At this time, only notes are displayed and it is a huge step back compared to what we have on production.
- In the editor's notes panel: only meaningful notes made by collaborators and other users.

Is it technically possible to make it work this way? I am not insisting on changing the video activity feed immediately, this can wait until some point in the future, but without a detailed collaboration history we may have a very hard time when incidents start happening in production, either due to bugs or because of users/admins messing things up.

**Comment by bendk** [comment]
I just fixed the collaboration details page.

The video page will work somewhat like that, but one complication is that there can be multiple teams working on collabs for a video.  So what we're going to have is different views of the video page, depending on your context.  So if you navigate to the video page from the work team, you'll see one listing.  If you go there from an evaluation team you'll see a different listing.

**Comment by PCF-Testing** [comment]
Generally looks good. The collab detail and team activity feed look as expected. The video feed does not have the collab-related activity, but I think we could live with it for the time being.

If a collab goes through VR process, the admins in the team that owns the video cannot see on the collab detail page the events related to the external evaluation. They can only see their own in-team evaluations and final endorsements by evaluators. Is this much of an issue?

**Comment by PCF-Testing** [comment]
Deployed.
