### ISSUE TITLE
Allow partner accounts to create other partner accounts via the API

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2362]

**Comment by PCF-Testing** [comment]
Verified on a local instance.

In negative testing, an attempt of a non-partner account to create a partner user (with "is_partner":True in payload) results in 201, but the created account has a value different from the specified in the request ("is_partner":False). I think the system should return a 403 when a non-partner user tries to create a partner account. However, since the feature is needed quickly, I am going to create a PR as is.

**Comment by PCF-Testing** [comment]
Deployed.
