### ISSUE TITLE
subtitle actions API permissions

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2375]
The subtitle actions API doesn't seem to have the right permissions.  You should only be able to view the endpoint if you have permission to view the video and you have permission to view the subtitles.

The endpoint is here: `/api/videos/[video-id]/languages/en/subtitles/actions`

**Comment by bendk** [comment]
While testing I noticed that on some endpoints you would see the actions and on others you would get an exception.  Hopefully the fix should address both.

**Comment by PCF-Testing** [comment]
This one is a bit hard to test because we have so many team types, privacy/workflow setups, user roles, and subtitle states - all together this yields a ton of possibilities.

Some issues detected so far:
- non-members can POST actions to *old teams without tasks where only members are allowed to edit* - they shouldn't
- *simple teams* - non-members get 403 on GET, 200 on POST (publish). Should be 200 in both cases?
- *ensemble teams* - non-members get 403 on GET, 200 on POST (publish). Should be 403 in both cases.
- *collab team* - a team member gets a 500 on POSTing (endorse) to the subtitles that are being worked on by another user.

Also, users get 500 when trying to POST an action to a language where no subtitles have been created yet. Shouldn't it be 405 instead?

**Comment by bendk** [comment]
For this ticket, I don't think we need to test all the teams types.  I think there's only 2 cases: the user can edit the subtitles or not.  If they can edit, then they should be able to use GET/POST, if not then they should get a 403 error.  I will try to fix those other issues with 500 responses and what-not, but I don't think you need to test all possibilities.

Note that this is slightly different then what I said in the description.  I think you should only be able to see the actions if you can edit the subtitles, not just view them.

**Comment by bendk** [comment]
So I think it should have been 403 status codes for the POST requests.  I just pushed a change that fixes that.

I wasn't able to get a good setup to test the 500 error when POSTing subtitles.  I think it would be better to return a 400 status code (405 is for when the method is not allowed at all).  But that seems like a different issue to me.

**Comment by PCF-Testing** [comment]
Generally looks good, with the small exception of https://github.com/pculture/amara-enterprise/issues/471.  Would it be better/faster/easier to fix it now while we are at it, or should I make a PR instead?

**Comment by PCF-Testing** [comment]
Marking as Waiting for Deploy.

**Comment by PCF-Testing** [comment]
Deployed.
