### ISSUE TITLE
Team Video page: tools to calculate total runtime for videos

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2384]
To bill enterprise clients, we want to calculate the total runtime for a set of videos.  I think we want 2 features to do this:

- On the video page, we should list the total duration of all videos
  - If filters are applied, then it should only be the videos that match the filter
  - If some videos have unknown durations, we should report that as well
- We should add a way to filter by the added_by date.
  - I think this should allow a range -- we will have 2 inputs one for the start date and one for the end date.

**Comment by bendk** [comment]
This is most important for new-style teams, but we should also add some support for old-style teams as well.

**Comment by syl22-00** [comment]
These should be done, in branch gh-2384:

* It shows the total duration of videos on page, text differs if this duration is partial because of some videos lacking it.
* videos can be filtered according to their creation date. It adds a date picker. Performance of querying with those filters might be slow because the `created` field is not indexed.
* Since `created` is a datetime and we only use date, it implies the filters are for midnight starting the day, not sure if it can be confusing sometimes.
* For now it is on new teams.

**Comment by bendk** [comment]
Sylvain implemented the date picker part of this ticket.  I think the duration part was handled by the special page that displayed durations.  Closing this one.
