### ISSUE TITLE
Handle different video durations from the video API and external APIs

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2387]
We should decide what to do in the following corner case:  Someone creates a video via the API and specifies a duration then when we query the duration from the video site (or mp4 header) we get a different value.

I think the best policy would be to ignore the value from the API client in this case.
  - We should make this clear in the API documentation
  - I believe this already happens, but we should include the new duration in the return data for the request.

**Comment by syl22-00** [comment]
This was done in branch gh-1113 so that it can be tested. 

* Video duration specified in API while creating videos is only used if video duration is not determined by provider or file header.
* Video duration specified in API while updating videos is only used if video duration is not already specified. In particular, if duration was previously set through the API, it can not be changed.
* Made sure the actually used duration is returned by the API call
* Documented the policy.

**Comment by PCF-Testing** [comment]
Looks good to me.

**Comment by syl22-00** [comment]
This was deployed.
