### ISSUE TITLE
Text in editor review step not displayed correctly

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2444]
OK for initial editing steps, however display for review / approve is not styled correctly.

![image](https://cloud.githubusercontent.com/assets/299270/12072797/2c11838a-b0c2-11e5-9867-877134f2c504.png)

**Comment by PCF-Testing** [comment]
I think this ticket is about help text having font weight 16 instead of 12, which is the standard format for help text:

![screenshot from 2018-09-27 02 08 57](https://user-images.githubusercontent.com/288455/46135638-801a6b80-c1fa-11e8-8b1b-f6c4df1d6e45.png)
(regular editor)

vs.

![screenshot from 2018-09-27 02 09 35](https://user-images.githubusercontent.com/288455/46135660-8d375a80-c1fa-11e8-9ae9-d7a6ecd4914b.png)
(review editor)
