### ISSUE TITLE
Ingesting videos quickly

### ISSUE THREAD

**Issue by syl22-00** [pculture/unisubs#2445]
We should add ways to add videos to teams in batch:
- [x] Form to add multiple video urls at once
- [ ] Inputting a CSV file, fields would be: URL, title, description, duration.

When ingesting, the PM would also have a few options:
- [x] Add videos to a project
- [ ] Create pro-requests for each video for a list of languages

**Comment by bendk** [comment]
Just had a call with the OD team and got some slightly updated requirements on the CSV form.

- The columns in the CSV file should be:
  - Project Name
  - URL
  - Title
  - description
  - duration (optional)
  - primary audio language (optional)
  - transcript URL (optional link to a subtitle file for the primary audio language)
- There should be an input to select the the client team to add the videos to
- If we see a project name that doesn't exist, create a new project
- There should also be a checkbox to split projects into 1-hour batches.  This means that:
  - We append "-Batch1", "-Batch2", "-Batch3" etc to each project name.  We then split up the videos so that each batch has just under 1 hour of videos

**Comment by syl22-00** [comment]
@PCF-Testing Could you take a look at the gh-2445 branch, the form to add team videos (new style teams) can now take any number of URLs.

**Comment by PCF-Testing** [comment]
@syl22-00: @bendk: @deanjansen:

Took a stab at it locally, found that:
- The change applies to new teams only, but not to task-based teams
- Each additional URL needs to be pasted separately, with an extra click on add another link and into a separate entry field
![addmultiplevideos](https://cloud.githubusercontent.com/assets/288455/13495120/afa301e0-e0fd-11e5-81c1-3cdac810cb65.png)
Is it what is really wanted? I am not sure that multiple-URL form saves time and effort compared to repetitive use of single-URL form. The only advantage seems to be in placing all the videos into the same project without selecting the project each time (but the project could be set for the recently added videos with a bulk edit action).
Shouldn't it be a multiple line entry field that would accept multiple URLs separated by new line symbol? In this case, the user would only need to perform copy-paste once.

**Comment by bendk** [comment]
My feelings are:
  - The multiple URL form seems good for 2-4 videos.
  - The CSV import is good for huge/complex injests.
  - The multi-line textbox would be good if you wanted to import 5-20 videos, and didn't need the extra features of the CSV import (setting title, descirption, duration, etc).

Seems like we could:
  - Keep this change and do nothing else (if we don't think the 5-20 video import use case happens that often)
  - Keep this change and also add a form that uses a textbox with multiple lines (maybe the dialog could have 2 tabs?)
  - Replace this change with the textbox style one (if we think the 5-20 import use case happens more than the 2-5 count)

**Comment by deanjansen** [comment]
I'm going send this to Jenny & Marília and see if we can get them to weigh in. To keep things simple, I'll suggest that we could leave as-is OR have a single field for a bunch of URL's. (note: if we do the latter, maybe we could allow separation by comma, space, and/or carriage return?) 

Will report back what I hear from AoD team...

**Comment by deanjansen** [comment]
Feedback from both Jenny & Marília is that Sylvain's current system looks preferable to a single field, especially if there's a CSV import for larger batches. So I think we can leave it as-is UX-wise.

Also, needless to say, they're both enthusiastic about this feature.

**Comment by PCF-Testing** [comment]
OK, if this dialog stays, here are a few nitpicks:

- [ ] The dialog is titled "Add Video" vs the button's caption, "Add Videos". Should be multiple in both cases

- [ ] Custom thumbnail setting does not work

- [ ] Horizontal dividers between Video URL: caption and add another link are non-uniform in color - the left part is darker than the normal color of the dividers

**Comment by syl22-00** [comment]
@PCF-Testing the CSV upload should be done and working well. The button is available in the videos page for collab teams for superuser and staff users.

**Comment by syl22-00** [comment]
Transcript file URL is now read and processed. Subtitle type of the file is processed from the extension (URL should look like `http://example.com/subtitles/file.srt`).

**Comment by PCF-Testing** [comment]
Regarding the dialog:

I think the text (and the concept of the CSV file) should be simplified:

"Your file should be a CSV file, with the first line being the header. The columns should be as follows:\n
Project name, Video URL, Title, Description, Duration, Primary audio language code, Transcript URL\n
Video URL is a mandatory field; the other fields can be left blank.

A CSV file can be created with a text editor or using the export function of a spreadsheet editor. _(period missing)_

Upon completion, you will receive _(not recieve)_ a summary by email."

**Comment by deanjansen** [comment]
Would it be simpler to offer a template CSV that people can download it, fill it out, and re-upload?

"Please use this [CSV Import Template](url) as the basis for your import. The Video URL field is mandatory, but all other fields can be left blank.

A CSV file can be created with a text editor or using the export function of a spreadsheet editor.

Upon completion, you will receive a summary by email."

**Comment by syl22-00** [comment]
Following the suggestions:
* Modal content is the same as what @deanjansen suggests, including template download
* Content of header is ignores
* CSV file must have 7 columns to be valid, but only URL columns needs to be non-empty.
* In case of illegal duration or language code (as well as transcript URL), the field is ignored, but the file is still added.
* In the summary email, messages are now better formatted, as a list.

**Comment by deanjansen** [comment]
@syl22-00 Noting the AoD request for "Set original video language during import." If you prefer I start a separate ticket, please just nudge me.

**Comment by syl22-00** [comment]
This is done in the branch (in the modal to add batch of videos, there is now a language selector that works the same as the project and thumbnail inputs)

**Comment by PCF-Testing** [comment]
- [ ] 5 tests broken on the branch:

======================================================================
ERROR: test_add (teams.tests.test_forms.AddTeamVideoFormTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 134, in test_add
    form = self.make_form({'video_url': self.url})
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 131, in make_form
    data=data, files=files)
  File "/opt/apps/amara/apps/teams/forms.py", line 1430, in __init__
    NewAddTeamVideoDataForm.__init__(team, *args, **kwargs)
TypeError: unbound method __init__() must be called with NewAddTeamVideoDataForm instance as first argument (got Team instance instead)

======================================================================
ERROR: test_add_non_team_video (teams.tests.test_forms.AddTeamVideoFormTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 166, in test_add_non_team_video
    form = self.make_form({'video_url': self.url})
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 131, in make_form
    data=data, files=files)
  File "/opt/apps/amara/apps/teams/forms.py", line 1430, in __init__
    NewAddTeamVideoDataForm.__init__(team, *args, **kwargs)
TypeError: unbound method __init__() must be called with NewAddTeamVideoDataForm instance as first argument (got Team instance instead)

======================================================================
ERROR: test_add_with_project (teams.tests.test_forms.AddTeamVideoFormTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 158, in test_add_with_project
    'project': project.id,
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 131, in make_form
    data=data, files=files)
  File "/opt/apps/amara/apps/teams/forms.py", line 1430, in __init__
    NewAddTeamVideoDataForm.__init__(team, *args, **kwargs)
TypeError: unbound method __init__() must be called with NewAddTeamVideoDataForm instance as first argument (got Team instance instead)

======================================================================
ERROR: test_add_with_thumbnail (teams.tests.test_forms.AddTeamVideoFormTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/utils/test_utils/monkeypatch.py", line 205, in wrapper
    return func(self, mock_obj, *args, **kwargs)
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 147, in test_add_with_thumbnail
    'thumbnail': thumb_file,
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 131, in make_form
    data=data, files=files)
  File "/opt/apps/amara/apps/teams/forms.py", line 1430, in __init__
    NewAddTeamVideoDataForm.__init__(team, *args, **kwargs)
TypeError: unbound method __init__() must be called with NewAddTeamVideoDataForm instance as first argument (got Team instance instead)

======================================================================
ERROR: test_cant_add_team_video (teams.tests.test_forms.AddTeamVideoFormTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 176, in test_cant_add_team_video
    form = self.make_form({'video_url': self.url})
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 131, in make_form
    data=data, files=files)
  File "/opt/apps/amara/apps/teams/forms.py", line 1430, in __init__
    NewAddTeamVideoDataForm.__init__(team, *args, **kwargs)
TypeError: unbound method __init__() must be called with NewAddTeamVideoDataForm instance as first argument (got Team instance instead)

- [ ] The title of "Add Videos" dialog reads "Add Video" (should be multiple)

- [ ] "Add Videos from CSV" dialog has the following sentence: "A CSV file can be created with a text editor or using the export function of a spreadsheet editor" displayed twice. The second instance is not needed.

CSV form can be accepted by the system with fewer than or more than 7 columns. The only real limitation is that the video URLs must be in column 2 - otherwise, the file will still be accepted but the videos won't get imported. I don't think this should be much of an issue unless AOD PMs disagree.

**Comment by PCF-Testing** [comment]
- [ ] If the Language column contains a value not matching (after conversion to lowercase string format) any language supported by Amara, just ignore the value and report it in the emailed summary

**Comment by syl22-00** [comment]
@PCF-Testing all raised issues should have been fixed now

**Comment by PCF-Testing** [comment]
Works well on all the aforementioned counts.

Last (hopefully!) thing - as we have discussed on a slack convo, bulk import cannot match a project name (not slug!) to an existing project in the team - e.g., I used the following file:

Project,URL,Title,Description,Duration,Language,Transcript
Batch 3 (03.24.2016),https://www.youtube.com/watch?v=VcXTFRXenwI,,,3600,ru,
Batch 3 (03.24.2016),https://www.youtube.com/watch?v=snFg0ynxTNo,,,7200,ru,

The system reports successful video submission, but actually does not import anything at all, nor does it report the issue in the email summary.

Are we going to support matching projects by name in bulk import? I'd suggest doing the following:
1) Searching for a match in existing projects by slug
2) Searching for a match in existing projects by name
3) Finally, if no match is found, create a new project with the value from column 1 as name.
Does this approach make sense?

**Comment by syl22-00** [comment]
I pushed a change to do 2 and 3. I can add one if necessary.

**Comment by PCF-Testing** [comment]
Implemented, except for splitting batches into 1 hour long chunks - made a separate ticket for that, since the current ticket is too feature rich.

**Comment by syl22-00** [comment]
@PCF-Testing the issue you found with language code not being correctly set was fixed

**Comment by PCF-Testing** [comment]
Deployed.
