### ISSUE TITLE
Amara Embeds Not HTTPS. Insecure Content Warnings.

### ISSUE THREAD

**Issue by itsalljustaride** [pculture/unisubs#2471]
Embedded players from Amara are not being delivered over ssl/https, so putting them on ssl/https protected pages trips insecure content warnings, and the videos do not appear. This means, in my case, that placing them on pages in a course LMS such as Canvas or Blackboard is not possible, necessitating linking out to a completely separate insecure, non-SSL page with the embed on it.

**Comment by bendk** [comment]
The issue is that some of the video providers don't support https, so we force http which always works.

Maybe we can detect if the embedder itself is loaded via https and then load the players via https.  This will fail for certain players (brightcove in particular, and a small portion of html5 videos), but this seems okay since the person embedding amara is choosing https.

**Comment by syl22-00** [comment]
@itsalljustaride Actually embedder can be served through https. We suggest to have:
```javascript
<script type="text/javascript" src="//amara.org/embedder-iframe">
</script>
```
If you get the embded code from the amara website, you get `http`, if you get it from the embedder itself, you get `//`. So I would treat this issue as: making amara give embed code with `//`.

**Comment by syl22-00** [comment]
* `Get Embed Code` modals now give embedder script URL with `https` (branch gh-2471).
* Wiki entry now gives embedder script URL with `https`

**Comment by PCF-Testing** [comment]
Deployed
