### ISSUE TITLE
Re-implement youtube language code mapping

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2523]
We used to have a unilangs mapping that mapped youtube codes to amara codes, but it didn't work so we stopped using it.  It turns out that we do need a mapping, at least for a few codes.  To start with it should include this map:

Amara Code  | YouTube Code
------------------ | ----------------------
zh-cn              | zh-Hans
zh-tw              | zh-Hant

**Comment by bendk** [comment]
This should be fixed for both syncing and fetching.  You'll need an updated unilangs version.  Probable the simplest way to get that is dev build.

**Comment by PCF-Testing** [comment]
Actually we already have "compatibility" language codes zh-hans and zh-hant in the system:
http://www.amara.org/en/admin/subtitles/subtitlelanguage/?language_code__exact=zh-hans - Chinese (Simplified Han)
http://www.amara.org/en/admin/subtitles/subtitlelanguage/?language_code__exact=zh-hant - Chinese (Traditional Han)
Is there any way we could use these codes for specific tasks rather than map zh-cn to zh-hans and affect all the other users' (including TEDx) subtitles?

**Comment by PCF-Testing** [comment]
@bendk, @deanjansen: we have discussed this issue a few times, but I am still unsure whether we are going ahead with this change or use the existing codes instead.

**Comment by bendk** [comment]
I think someone needs to talk with TED and our other partners and ask them this question:

Would you rather have we use zh-hans for your youtube videos?  I believe this shows up as something like "Chinese (Simplified)" rather than "Chinese (China)".  We should double check the exact strings.  We should also ask the same question for zh-hant/zh-tw.

A side issue is videos with zh-cn subtitles that have already been synced.  In this case, I think we should just keep syncing with the same language code rather than create a new one.

Based on what their answers are, we can decide if we want to make the change for all partners, some partners, or no one.

**Comment by bendk** [comment]
Okay, since reaching out to our partners is a complex process, I'm going to try a slightly flexible solution.  I'm going to add a flag to the youtube account object called "enable language mappings".  For current accounts this will be off by default.  For new accounts it will be on by default.  If a partner tells us they want the new behavior (or the old behavior), you'll be able to update it via the django admin.

If the flag is enabled, then I'm going to implement the behavior I describe above:
  - When syncing:
       - Normally we sync `zh-cn` subtitles to YouTube using the `zh-hans`
       - If there's already a track on yotube for `zh-cn`, then we will use that rather than create a second track
  - When importing:
       - `zh-hans` subtitles on yotube will get imported as `zh-cn`
       - `zh-cn` will also get imported as `zh-cn`
  - The same behavior will be used for `zh-tw`/`zh-hant`

**Comment by bendk** [comment]
One more corner case: if there are subs in both zh-cn and zh-hans, then I think we will used the non-mapped code (zh-cn).

**Comment by bendk** [comment]
Okay, that new system is implemented.  I think this should work well for all parties.

**Comment by PCF-Testing** [comment]
@bendk: could you please update the branch with the latest changes? Thank you!

**Comment by bendk** [comment]
@PCF-Testing merged.

**Comment by PCF-Testing** [comment]
- [ ] /admin/externalsites/youtubeaccount/account_id/  requires Import team as a mandatory parameter. With Import team not set, it is impossible to save the form with changed mapping flag; can it be made optional?

- [ ] With language mapping turned on, Chinese Traditional on Amara is exported to YouTube as Chinese (Taiwan) rather than the expected Chinese Traditional

- [ ] During the import of subtitles from YouTube to Amara, existing subtitles with a locale (es-es, zh-hans), causes an exception and blocks import:

worker_1 | ERROR 2016-05-19 04:48:36,594 celery.worker.job Task externalsites.tasks.fetch_subs[7cec8d71-fd9e-428f-b971-9e25a7c57757] raised exception: KeyError(u'es-es',)
worker_1 | Traceback (most recent call last):
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 224, in trace_task
worker_1 |     R = retval = fun(*args, **kwargs)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 403, in __protected_call__
worker_1 |     return self.run(*args, **kwargs)
worker_1 |   File "/opt/apps/amara/apps/externalsites/tasks.py", line 135, in fetch_subs
worker_1 |     subfetch.fetch_subs(VideoUrl.objects.get(id=video_url_id))
worker_1 |   File "/opt/apps/amara/apps/externalsites/subfetch.py", line 50, in fetch_subs
worker_1 |     fetch_subs_youtube(video_url)
worker_1 |   File "/opt/apps/amara/apps/externalsites/subfetch.py", line 74, in fetch_subs_youtube
worker_1 |     language_code = convert_language_code(language_code.lower())
worker_1 |   File "/opt/apps/amara/apps/externalsites/subfetch.py", line 38, in convert_language_code
worker_1 |     return unilangs.LanguageCode(lc, 'youtube').encode('unisubs')
worker_1 |   File "/opt/src/amara/unilangs/unilangs/unilangs.py", line 1213, in __init__
worker_1 |     self._code = standard_dict[language_code]
worker_1 | KeyError: u'es-es'



worker_1 | ERROR 2016-05-19 05:06:01,280 celery.worker.job Task externalsites.tasks.fetch_subs[083b7e46-e53d-4335-9931-67fba1e988be] raised exception: KeyError(u'zh-hans',)
worker_1 | Traceback (most recent call last):
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 224, in trace_task
worker_1 |     R = retval = fun(*args, **kwargs)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 403, in __protected_call__
worker_1 |     return self.run(*args, **kwargs)
worker_1 |   File "/opt/apps/amara/apps/externalsites/tasks.py", line 135, in fetch_subs
worker_1 |     subfetch.fetch_subs(VideoUrl.objects.get(id=video_url_id))
worker_1 |   File "/opt/apps/amara/apps/externalsites/subfetch.py", line 50, in fetch_subs
worker_1 |     fetch_subs_youtube(video_url)
worker_1 |   File "/opt/apps/amara/apps/externalsites/subfetch.py", line 74, in fetch_subs_youtube
worker_1 |     language_code = convert_language_code(language_code.lower())
worker_1 |   File "/opt/apps/amara/apps/externalsites/subfetch.py", line 38, in convert_language_code
worker_1 |     return unilangs.LanguageCode(lc, 'youtube').encode('unisubs')
worker_1 |   File "/opt/src/amara/unilangs/unilangs/unilangs.py", line 1213, in __init__
worker_1 |     self._code = standard_dict[language_code]
worker_1 | KeyError: u'zh-hans'

**Comment by bendk** [comment]
I just pushed a fix for 2 of the issues.  I can't reproduce the third.  Were there already subtitles with `zh-tw` as the language code?  In that case, we will use the same code rather than changing it.

**Comment by PCF-Testing** [comment]
Re #3: the video is https://www.youtube.com/watch?v=3tDUm8Z7HZg
On Amara (local branch), the video had English, zh-cn, zh-tw. I used resync version button to push subtitles to YT. The mapping for the account is on.

**Comment by bendk** [comment]
The question is what was the language codes for the subtitles were on youtube.  If there are already subtitles with the language code zh-cn or zh-tw, then we use those codes rather than change them to avoid duplicate tracks.

**Comment by PCF-Testing** [comment]
Just 'en' - everything else had been purged prior to test.

**Comment by bendk** [comment]
That's really weird, I tested with both and it worked.  Maybe we can merge to staging and check it out there?

**Comment by PCF-Testing** [comment]
I've tried a lot locally, with different channels and videos, and always got the same results. So OK, let's give it a try on staging.

Also, it does not make sense that the subtitles successfully exported from Amara to YouTube (zh-tw,zh-hans, zh-hant) are skipped when subtitles get imported from YouTube during video submission. However, I don't think it is a good idea to try solving this problem by applying matching rules. Instead, we badly need a dialog that would allow to pull any particular subtitle language from YouTube to the video on Amara, specifying the desired target language.

**Comment by bendk** [comment]
Something is totally off, I'm not sure what it is.  We do the mapping in both directions, so we should import them from youtube without issues.  I guess we need to test on staging to see what's happening, that way I can check out the team settings, run things in the shell, etc.

**Comment by PCF-Testing** [comment]
@bendk: ok, I have been able to reproduce wrong mapping on staging:
https://www.youtube.com/watch?v=deNXEgTBzdo
https://staging.amara.org/en/videos/I1hnUyPCrtqZ/info/seattle-aquarium/
http://staging.amara.org/en/admin/externalsites/youtubeaccount/34413/
(All the previously existing subtitles for this video had been removed from Amara and YouTube prior to beginning the test. Test started with no subtitles on either side. Subtitles were synced in en -> zh-cn -> zh-tw order.)

**Comment by bendk** [comment]
Doh!  I forgot to push my changes to unilangs.  I just pushed them and am redeploying staging now.  I think things should work much better.

**Comment by PCF-Testing** [comment]
Did deploy go well? zh-tw still keeps exporting as Chinese (Taiwan).

**Comment by PCF-Testing** [comment]
Retested locally on staging branch.

Language codes for exporting subtitles in Chinese language are now mapped as expected. However, I am seeing other problems with YouTube syncing:
- On submitting videos from linked YT channels, subtitles do not get imported - regardless of mapping on/off and the list of subtitle languages for the video. No errors appear in the logs, import just silently fails
- On completing subtitles (uploading 100% complete or clicking Publish in the editor), subtitles do not get synced to YT. It takes a click on re-sync version button to push subtitles to YT.

**Comment by bendk** [comment]
I think this may be an issue with your worker process.  Both work okay for me.

**Comment by PCF-Testing** [comment]
This one has been deployed and seems to work fine on production.
