### ISSUE TITLE
Don't delete videos from the DB

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2583]
Right now we provide an option for team admins to delete videos from amara.  We currently implement it by deleting the row in the database, but that's not ideal because related rows get deleted as well (for example activity rows).

Instead we should have a deleted flag that we set.  When the flag is set:
- The video page always returns a 404/403
- The video is removed from the search index.  This should remove it from both the search page and the team videos page

We should also have a way to undelete to reverse the action.

**Comment by PCF-Testing** [comment]
This issue involves the option to re-submit the video from scratch, as it had never been in the system before. Some special cases include:
- Importing subtitles from YouTube, if applicable. 
- Ingesting a Vimeo order (after "deleting" the video submitting a new video must be feasible, possibly with a different primary language).

**Comment by bendk** [comment]
That's a good point.  Currently we allow that.  With the deleting option, I think we should not allow it.  The reason being that if a team has a good reason to delete it, then it probably shouldn't be allowed to be in any other team or the public section.

**Comment by PCF-Testing** [comment]
https://github.com/pculture/unisubs/issues/1938 could take care of YT import gone wrong / outdated.

V. orders are a bit of more issue though - we delete the video when cancelling language-mismatch orders so that a new order could be successfully submitted. If the video with a wrong primary language remains in the system, subtitles cannot be ordered for it anymore and an error appears on the V. side

**Comment by bendk** [comment]
Interesting, so looks like we need one of the following:
  - Method for admins to nuke a video from the DB
  - Better way to handle the language mismatch
