### ISSUE TITLE
Allow `create_login_token` in API user update 

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2592]
Login tokens expire after 2 hours, so there's no current way to handle the following case:
  - Partner creates an account for one of their users
  - User reads their email 4 hours later
  - User tries to log in, but their token is now invalid.

To work around this case, we should allow create_login_token to be a valid input for an update request as well as a create request.  This allows partners to work around this issue by saving their API key when creating the user, then performing an update request with create_login_token to get a new login token.

**Comment by PCF-Testing** [comment]
Exception on attempt to use an expired token:

AttributeError at /auth/auto-login/0a2d502e5691d3854be774f01599fbf7fdb19301/

'LoginToken' object has no attribute 'expired'

Request Method: 	GET
Request URL: 	http://unisubs.example.com:8000/en/auth/auto-login/0a2d502e5691d3854be774f01599fbf7fdb19301/
Django Version: 	1.4.21
Exception Type: 	AttributeError
Exception Value: 	

'LoginToken' object has no attribute 'expired'

Exception Location: 	/opt/apps/amara/apps/auth/models.py in is_valid, line 697

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/opt/apps/amara/apps/auth/views.py" in token_login
  231.         if lt.is_valid():
File "/opt/apps/amara/apps/auth/models.py" in is_valid
  697.         if self.expired():

Exception Type: AttributeError at /auth/auto-login/0a2d502e5691d3854be774f01599fbf7fdb19301/
Exception Value: 'LoginToken' object has no attribute 'expired'


Expected: instead of an exception, the user should see a graceful error message or just see home page as a non signed in user.

**Comment by bendk** [comment]
That one should be fixed now

**Comment by PCF-Testing** [comment]
Confirming it is fixed for expired logins.

For new login recreated with the use of the user's API, the exception is as follows:

TypeError at /auth/auto-login/70fd621a49813fe908b73018b1d21f024f07edb6/

'bool' object is not callable

Request Method: 	GET
Request URL: 	http://unisubs.example.com:8000/en/auth/auto-login/70fd621a49813fe908b73018b1d21f024f07edb6/
Django Version: 	1.4.21
Exception Type: 	TypeError
Exception Value: 	

'bool' object is not callable

Exception Location: 	/opt/apps/amara/apps/auth/models.py in is_valid, line 697

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/opt/apps/amara/apps/auth/views.py" in token_login
  231.         if lt.is_valid():
File "/opt/apps/amara/apps/auth/models.py" in is_valid
  697.         if self.is_expired():

Exception Type: TypeError at /auth/auto-login/70fd621a49813fe908b73018b1d21f024f07edb6/
Exception Value: 'bool' object is not callable

**Comment by bendk** [comment]
Okay, I think my second blind fix is going to be good.

**Comment by PCF-Testing** [comment]
Looks good now.

**Comment by PCF-Testing** [comment]
Deployed.

**Comment by deanjansen** [comment]
Hey Ben, I was following up on this to see if the partner had figured it out and noticed that the documentation doesn't seem to reflect the user's option for including create_login_token in the update request. 

Should that be adjusted in the comments?

![screen shot 2016-08-02 at 2 58 42 pm](https://cloud.githubusercontent.com/assets/216145/17341271/c96a8d64-58c1-11e6-8795-3595b9993403.png)
