### ISSUE TITLE
Redefine following videos and subtitles

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2593]
- all assignees automatically become followers of the subtitles
  - Note: there's already a setting in their profile to disable following all subtitles you are assigned to.
- for collab teams, followers of subtitles get notified when:
   - A user endorses, and the version is different than the previous assignee's endorsed subtitles
   - A manager changes the request state, and the version is different than the previous assignee's endorsed subtitles
   - A manager/admin updates the subtitles after the request is complete

- video followers should receive email and onsite alerts when:
  - video title or description changes
  - any of the actions for subtitles on the video occur

See also https://github.com/pculture/unisubs/issues/621

![neweditsmessage](https://cloud.githubusercontent.com/assets/288455/16412630/245bd1a2-3ce2-11e6-931c-84c058be1d1a.png)

**Comment by bendk** [comment]
This should be fixed in the branch.

**Comment by PCF-Testing** [comment]
Alerts do get sent on the branch.

One thing that is wrong about the implementation in gh-2593 - in task-based and collab-based teams "New edits" notifications should not be sent while the new language is being created, QA-ed, and published. Notifications should start only from the first post-publish edit. Until that moment, they only confuse users because other messages are (or will be) sent - "Your subtitles have been reviewed", "Your subtitles have been approved and published", etc.

**Comment by bendk** [comment]
So to fix this one properly I think we're going to have to do some work on some of our legacy code here.

The way the messages currently get sent is in the videos.tasks.video_changed_tasks() celery task.  That task has an optional argument called new_version_id.  When it's sent we:
  - Send the message
  - Create a BillingRecord using the really old billing code

To fix this I think we should:
  - Remove the new_version_id parameter from video_changed_tasks().  Update all existing code not to pass that value.
  - Add code at the end of subtitles.pipeline.add_subtitles() to send the message
  - Add a way for the subtitle workflow to prevent the message from being sent.  For collab and task teams, we should prevent this message and send our own manual messages.
  - Double check that for task teams, we send the message for post-publish edits
  - Ensure that we send the message for other ways of adding a new version: rollback and the upload form.
 - The last issue is the fact that we're not creating a old-style billing record anymore.  I'm pretty sure that's fine because the new system has replaced it, but we should double check that.

I'm going to put this one on pause since I have a lot of other things to do, but hopefully we can address this semi-soon.

**Comment by bendk** [comment]
@PCF-Testing @kslottow should we put this one in a sprint?  I'm not sure how badly it's affecting users.  If it's not bad, then I would say just ignore it and make things work with collab teams.  If it is causing many users pain, then we should fix it.

**Comment by PCF-Testing** [comment]
The original issue seems to be OK - I've received a bunch or alerts about subtitle changes over the last 3 months. The bigger issue - notifications about collab status changes - is still there, but probably should be handled in a separate ticket. The sooner we start working on that, the better, to give us time to iron out the inevitable wrinkles.

**Comment by kslottow** [comment]
@bendk @PCF-Testing do we already have a separate ticket for this?  If not, can someone make one and put it in Discovery for Sprint 5?

**Comment by kslottow** [comment]
then it seems like we can reference it here and close this one.

**Comment by bendk** [comment]
Sounds great to me.  I'm just going to close this one.

If you search for notifications on the amara-enterprise repo, you see several issues.  I think we should create an epic for them though.

**Comment by kslottow** [comment]
> If you search for notifications on the amara-enterprise repo, you see several issues.  I think we should create an epic for them though.

Can you do that @bendk ?  I searched for "notifications" and it seemed like there was a lot of stuff that wouldn't belong in the epic (maybe "Notifications Improvements?").  Let's then put the epic and all the issues in the icebox for now, but we'll plan to take a closer look soon.

**Comment by bendk** [comment]
We just decided that this should work as follows:

- all assignees automatically become followers of the subtitles
  - There's a setting in their profile to disable this.  Also, the help text for that setting should explain what "following means"
- for collab teams, followers of subtitles get notified when:
   - A user endorses, and the version is different than the previous assignee's endorsed subtitles
   - The same if a manager changes the request state
   - A manager/admin updates the subtitles after the request is complete
