### ISSUE TITLE
Delete videos via API

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2720]
For team admins that can delete videos from their team, we should allow them to send a DELETE request to the API endpoint to do the same.

DELETE should result in the video being deleted, rather than removed from their team.

If there are any subtitles/collaborations on the video, they should also be deleted.

**Comment by kslottow** [comment]
Use case for this: when a project is created, and a video is created in that project, then the project is canceled, an admin should be able to delete the old video so that they can reassociate the video with a new project without a conflict like "this video already exists."

**Comment by syl22-00** [comment]
Done in branch gh-2720, although some housekeeping might be necessary.

**Comment by bendk** [comment]
Can you add the user param to the video.delete() call?  That way we log the deletion.

**Comment by PCF-Testing** [comment]
@bendk: how about the previous activity entries related to the deleted video (such as video-added, video-moved, etc.). Should they be kept or deleted?

**Comment by PCF-Testing** [comment]
On attempt to remove a video from an old-style, task-based team via UI (Remove|Permanently remove), the following exception is raised:

DatabaseError at /teams/remove/video/404/
(1366, "Incorrect string value: '\\xE6\\x85\\xA2\\xE9\\x8F\\xA1...' for column 'title' at row 1")
Request Method:	POST
Request URL:	http://unisubs.example.com:8000/en/teams/remove/video/404/
Django Version:	1.4.21
Exception Type:	DatabaseError
Exception Value:	
(1366, "Incorrect string value: '\\xE6\\x85\\xA2\\xE9\\x8F\\xA1...' for column 'title' at row 1")

This is a regression because on production the same video can be removed without any problem. Video URL: https://www.youtube.com/watch?v=G-KLXdeLEBw

**Comment by PCF-Testing** [comment]
There is also one more related issue here, which is not specific to the branch.

Once you delete a video from a team (say, old-style team) - either through the UI or via API - an empty video object stripped of URL, tasks/collabs, activity log, and subtitles, remains in the public domain of the site. This also happens on production - see, for example, http://www.amara.org/pt-br/videos/zhCnK0lfaWZw/ Although technically this bug does not break the requirement in this ticket, i.e. does not prevent the original video URL from being re-submitted, but it is still not good because this "ghost" entry exposes the ID, title, and some other information on the former video.

Is a separate ticket needed for this issue?

**Comment by kslottow** [comment]
We should address that privacy issue as soon as possible in a separate ticket because it is important not to expose any info from the deleted video: I made pculture/amara-enterprise/issues/1101 for that.

**Comment by syl22-00** [comment]
@PCF-Testing I can add then permanently delete this video, from a old style team. Could it be from somewhere else?

**Comment by PCF-Testing** [comment]
Deployed.
