### ISSUE TITLE
Finish December API updates

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2730]
We did a bunch of updates in december to the API.  Seems like things are working okay at this point so we should finish the last touches on them:

- Remove the ViewSetSwitcher code.  At this point it's not doing anything since the switcher date is passed
- Remove the safe team member endpoint.  We said this one was going away in the messages.
- Update the user activity endpoint to accept different user identifiers.  We said we would update this, but we never did.
- Update the user-activity-uri field on the user endpoint to return URLs using the secure IDs.

**Comment by bendk** [comment]
We should probably send out a message to our partners saying we're going to do this, even though it's all backward compatible.  Here's an attempt at this:

We are making some small, backward compatible, changes to our API to finish up the work done in December around user identifiers.  This should not require any change of code on your side, please tell us if you think it could affect you.  Here are the changes:

- The user activity endpoint will now accept all types of user identifiers, not just usernames.  Both of these URLs will now work:
  - /api/users/[username]/activity/
  - /api/users/id$[secure_id]/activity/

- The user endpoint will now return links to the secure_id version in the activity_uri field

**Comment by bendk** [comment]
Just checked in the code in the gh-2730 branch.  Things needing testing:
- User API endpoint
- User activity API endpoint
- All the endpoints in general could use a quick check.  As long as they don't crash they should be fine.

**Comment by PCF-Testing** [comment]
Got exception on attempt to view activity for a non-existent user (username misspelled) instead of a proper 404 response:

NameError at /api/users/maggie_/activity/
global name 'Http404' is not defined
Request Method:	GET
Request URL:	http://unisubs.example.com:8000/api/users/maggie_/activity/
Django Version:	1.4.21
Exception Type:	NameError
Exception Value:	
global name 'Http404' is not defined
Exception Location:	/opt/apps/amara/apps/api/views/activity.py in get_queryset, line 350

Similar exception when there is an error in the beginning of the user GUID, e.g. /api/users/id%24RPG3N3ogn1eFynSnocrw3VWAQy8nfZPuq1j93djQgVS/activity/ instead of /api/users/id%24QAG3N3ogn1eFynSnocrw3VWAQy8nfZPuq1j93djQgVS/activity/

I have the impression that when call is made by user GUID, not the whole ID is used to find matches - just some initial part of it. It is possible to use, for example, QAG3N3ogn1eFynSnocrw3VWAQy8nfZPuq1j93djabcd instead of QAG3N3ogn1eFynSnocrw3VWAQy8nfZPuq1j93djQgVS, and still get the same result set. Is it to be expected? 

Otherwise, the branch looks good; tried with unusual usernames that were causing trouble in enterprise-1043, and found no problem with them.

**Comment by bendk** [comment]
Should be fixed now.

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed.
