### ISSUE TITLE
Tasks cannot be unassigned through API

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2844]
PUT /api/teams/[teamslug]/tasks/[taskID]/ 
{"assignee": null}
returns
HTTP 400 Bad Request
Content-Type: application/json
Vary: Accept
Allow: GET, PUT, DELETE, HEAD, OPTIONS, PATCH

{
    "assignee": [
        "This field may not be null."
    ],
    "approved": [
        "This field may not be null."
    ]
}

Expected: "assignee" should be changed to null.

Reported: https://pculture.freshdesk.com/helpdesk/tickets/94160

**Comment by kslottow** [comment]
@bendk @PCF-Testing how hard is this to fix? TDS has been doing this manually for TED ever since this bug came up, so over a year. TED sends in a support ticket every time just asking us to please unassign this user.

If it's any substantial amount of work, maybe we shouldn't, to be consistent with not fixing task issues while we roll out the collab model.

**Comment by PCF-Testing** [comment]
There is no need to do this through support because a task can be easily unassigned through the UI. This fix was requested for unassigning tasks programmatically; this happened quite a while ago, so I don't have a clue if this is still needed.

**Comment by bendk** [comment]
I think we should close and just try to encourage people to move to collab teams.
