### ISSUE TITLE
Bug that shows Double subtitles inside Amara's subtitle editor's preview video player

### ISSUE THREAD

**Issue by BoQsc** [pculture/unisubs#2968]
Changelog: no public changelog entry.
Youtube subtitles no longer show in the video player inside the subtitle editor
===
# Problem-trace
Recently I noticed that Amara's subtitle editor  **//amara.org/en/subtitles/editor/xxxxxxxxx**/en )
has started to give out double subtitles. 
**It happens after starting playback.**
The preview window has:
- Youtube's subtitles
- Amara's editor's subtitles

Enabled and running at the same time, as the picture demonstrates below.

![html5_youtubeplayer_doublesubtitles](https://user-images.githubusercontent.com/21064622/31318590-874c0480-ac5d-11e7-828f-bce2a7e820d0.png)

# Quick-Fix/Patch

1. Listening to the **DOMContentLoaded** event, 
2. finding **#setting caption-window-_0** ID element
3. Changing the the **style** property's value of so called **display** to value **none**

```
document.addEventListener("DOMContentLoaded", function(event) {
	document.getElementById("caption-window-_0").style.display = "none";
  });
```

**Comment by kslottow** [comment]
Hi @BoQsc , we're going to fix this one soon! Thanks for reporting, and apologies for the extremely delayed response.

**Comment by danantonioreyes** [comment]
After giving it some thought while trying to fix this, I think there could be merit in seeing double subtitles. I can imagine it would sometimes be useful to see the subtitles from Youtube/other external site while also seeing the subtitles from the Amara editor.

I can think of two solutions for this problem:
1. Change the embedder code for the subtitle editor so that it disables Youtube subtitles from showing
2. Enable the embedded player's controls (play/pause, scrubber/seeker, subtitle options, etc.) -- this makes it possible for a user to show/hide the subtitles from Youtube/other external site at will--they can even choose which subtitle if there are multiple available from the external site. Downside of this is that there will be two play buttons and two scrubbers/seekers, and I'm pretty sure there is already a reason why we have the embedded player's controls disabled on the subtitle editor.

@kslottow @bendk what are your thoughts on this?

**Comment by kslottow** [comment]
I think we should disable YouTube subtitles from showing - it seems like extra work and extra clutter to enable hiding or showing both, and no one has asked for this, so my vote is that we opt for simplicity.

**Comment by danantonioreyes** [comment]
Implemented in https://github.com/pculture/unisubs/tree/gh-unisubs-2968

**Comment by Rachel36** [comment]
@danantonioreyes Enterprise-2968 has been verified.

**Comment by PCF-Testing** [comment]
@bendk: this one will have to be merged into the experimental editor as well.

**Comment by PCF-Testing** [comment]
Deployed.
