### ISSUE TITLE
Combine button assets

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3187]
We should merge the marketing and application SCSS for buttons.  We should also merge the JS if there is any differences.

One difference is in the height of the buttons.  The marketing page ones are much taller than the non-marketing page ones.  I think we should make the following buttons tall:

  - Buttons with the `tall` CSS class
  - Buttons on the marketing pages (maybe we give them all the tall class)
  - Buttons on at the phone/tablet resolution

**Comment by bendk** [comment]
Implemented in the gh-3187 branch.  Couple of notes here:

 - There were several stylistic differences and that's okay since marketing pages are somewhat special.  I added the `.marketing` class for buttons on the marketing pages.
 - I used the marketing styles for the videos/create page and the pricing table.

**Comment by PCF-Testing** [comment]
- [ ] Teal buttons on the marketing pages (e.g "Get Started" for the Enterprise Platform) and plum buttons still change their color on mouseover, but lime buttons (e.g. "Get Started" for the Free Platform) don't do it anymore. This feels like a bug, is this behaviour intentional? "Learn More" links also do not change their color on mouseover.

- [ ] In the UI language selector, "Cancel" button does not get highlighted on mouseover.

**Comment by PCF-Testing** [comment]
They all work great now except the bottom button on /recruitment/ page. Sorry, did not mean to nitpick!

**Comment by bendk** [comment]
Should be fixed.  The nitpicking is great!

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed.
