### ISSUE TITLE
Editor: subtitle stuck on screen after editing

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3201]
Steps to reproduce:
1. Open a subtitle set in an editor, e.g. https://amara.org/en/subtitles/editor/5Mo4oAj1bxOb/en/.
2. Seek to a subtitle, say, to 2:08.
3. Make an edit in the subtitle, e.g.  make the text read "... were terribly WRONG and should change".
4. Press TAB key to play the video.

Observed result: the video plays, the edited subtitle is stuck on the screen.
Expected: subtitles should be shown and hidden according to their start and end times.

**Comment by bendk** [comment]
So this was related to the issue that users reported yesterday.  I think there's been some confusion because the code that showed the subtitle on the video screen had some very weird quirks.

Can we clarify a related use case:

 - Subtitle X is at the current video playback time, and is shown in the video overlay
 - I click on subtitle Y to edit it
 - Which subtitle should now be shown on the video?

Based on the behavior before, it was subtitle Y -- the editing subtitle.  But it seems more consistent to show subtitle X.  In other words, can we make it so the subtitle shown on the video is always the subtitle as the current video time?

**Comment by PCF-Testing** [comment]
> can we make it so the subtitle shown on the video is always the subtitle as the current video time?

Subtitles can be untimed. Perhaps this is why the clicked subtitles is always shown on the screen.

This particular issue is more straightforward in the sense that X and Y in the described scenario are the same - you seek to the subtitle and then edit it.

**Comment by kslottow** [comment]
I think we can close this one, because we are testing a behavior in the experimental editor where we only show the subtitles at the current time in the video player. If users like it, we can use that behavior in the actual editor.
