### ISSUE TITLE
Legacy button missing in editor in some cases

### ISSUE THREAD

**Issue by allison-amara** [pculture/unisubs#3217]
Entered into an assignment in my Collaboration team on amara.org and the Legacy Editor button was missing. 
To get into the editor, I went to:
- Dashboard > Transcribe/Translate
- Management > Subtitle Details page > Transcribe/Translate

And each time the editor was missing the legacy button.

![legacy-button-missing.png](https://images.zenhubusercontent.com/5a5fb7694b5806bc2bc3298e/f9effe43-4911-4c4f-a7b3-f75de8a81760)

username: mallison
team name: Allison Collaboration Team
browser: Google Chrome
OS: Windows 10

This is particularly urgent because of the recent blog post requesting user feedback about the Legacy Editor.

**Comment by kslottow** [comment]
I was not able to reproduce on staging for a video not on a team 

I could reproduce on a collaboration team, by taking an assignment (I took an evaluation assignment)

**Comment by kslottow** [comment]
while trying to reproduce on a simple team on staging I saw a (maybe unrelated?) error where the marketing pages menu is displayed instead of the team header:

https://staging.amara.org/en/videos/t9y7c0O7zQis/info/for-harriet-kenzie-slottow-and-yuki-ishiguro/?team=demo-team-3-simple
user: kslottow

![screen shot 2018-05-22 at 2 29 20 pm](https://user-images.githubusercontent.com/22455700/40385542-8cd0d8c4-5dcc-11e8-8434-cde0fa5c8c23.png)

**Comment by bendk** [comment]
The legacy editor button doesn't show up for new-style team videos.  I believe the reason is that it doesn't support things like collab-endorse.
