### ISSUE TITLE
Fix corner cases with auto-removing the last blank subtitle

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3237]
The code to auto-remove the last subtitle is pretty weird.  I think we should only remove it in the following case:

 - User hits enter while in typing mode on the last subtitle, so we create a new blank one below
 - User clicks away without entering any text

We shouldn't remove it in these cases:

- Translation corner case:
  - Start a translation, there are tons of blank subtitles in the subtitle list.
  - Start editing the last subtitle, then click away to cancel.
- User manually inserts the subtitle:
  - User clicks the insert below button to insert a new subtitle at the end of the list
  - User starts editing the subtitle, then clicks away

This case is borderline to me, maybe we should auto-remove to since it's more consistent with the current behavior
- User hits enter to start a new subtitle
- User types in a bunch of text
- User hits backspace to remove all text
- User clicks away

**Comment by PCF-Testing** [comment]
It is in the specs of the editor that pressing ESC is supposed to delete the current subtitle if it is empty:

![screenshot from 2018-06-05 05 40 33](https://user-images.githubusercontent.com/288455/40976438-0acf1324-6883-11e8-9f20-b5c49f130235.png)

The changes on the branch break this feature. Are we sure we want to make this happen? If yes, then the list of shortcuts has to be updated.

**Comment by bendk** [comment]
I don't think we need to worry about breaking feature compatibility for a few reasons:
  - The feature doesn't make much sense (IMO) 
  - The functionality doesn't match that text -- it only happens for the last subtitle in the list -- and as far as I know there have been no complaints about this.  So I'm guessing it's not too important for most users.
  - We have another shortcut for deleting subtitles

So I think it's fine to change the functionality.  That said, if you or @kslottow think it's useful functionality, then that's another story.

**Comment by bendk** [comment]
For now, I just removed the shortcut from the dialog.  We can talk more about other solutions still, but I wanted to get all the editor fixes issues out of in-progress.

**Comment by PCF-Testing** [comment]
Well, there still seems to be some inconsistency about removing the last subtitle.

Suppose we are transcribing a video and appending a new subtitle cell at the bottom of the set with the use of "+New subtitle" or "Insert below" commands:

Case 1. Insert a new cell, do not type anything, click outside the cell (e.g. on the Notes panel). The new blank cell remains available.

Case 2. Insert a new cell, do not type anything, press ESC. The new blank cell disappears from the typing panel (however, if the timeline is shown and the previous subtitles are timed, the new subtitle remains displayed on deck).

Case 3. Insert a new cell, do not type anything, press CTRL+Z. The new blank cell disappears from the typing panel.

Case 4. Insert a new cell, type something, click outside the cell. The new cell and the text remain displayed.

Case 5. Insert a new cell, type something, press ESC. The new cell and the text disappear (however, if the timeline is shown and the previous subtitles are timed, the new subtitle remains displayed on deck).

Case 6. Insert a new cell, type something, press CTRL+Z. The new cell remains, the text disappears.

Cases 1,3,4, and 6 seem pretty straightforward and consistent with the general logic of the editor. Cases 2 and 5 stand out a bit. The "ghost" cell image left on the timeline in on-deck area definitely feels like a bug. ESC key removing both the text and the cell in a single stroke feels strange by comparison with case 6, but can be handy when you switch from typing to syncing (type text -> ENTER -> type more text -> ENTER -> repeat until the end of video -> ESC to remove the last unnecessary empty subtitle -> Start Syncing). However, ALT+DELETE could also work to remove the last cell instead of ESC. 

Not sure how to best handle these cases, should we keep the behaviour from cases 2 and 5?

**Comment by bendk** [comment]
Case 2 seems wrong for 2 reasons:
  - If I manually click on "insert new subtitle", then escape shouldn't delete it.  I really want to reserve that for only the case where the subtitle gets added by the enter key.
  - The ghost subtitle is just a bug

Case 5 also seems wrong for the reason above.

The other thing this gets me thinking about is the shortcut of ESC to revert the current edit.  I don't think that's so useful anymore now that we support undo.  It's also explained as "cancel the current edit", but to me that just means stop the edit, not revert the changes I've made.  I'm going to try changing that one, hopefully it makes sense to you too.

**Comment by PCF-Testing** [comment]
Yes, the latest changes in the way ESC key behaves do make sense to me.

One strange thing happens when the timeline is turned off and a new subtitle is appended with the use of ENTER key: once you press ENTER and get a new cell at the end, you can remove it with ESC (which seems OK), but not with a single CTRL+Z - it takes 2 hits on CTRL+Z to get rid of it. This feels like a bug to me.

**Comment by bendk** [comment]
So that corner case revealed issues with the code in general, so I had to change how we auto-remove the inserted subtitle.  Here's the new logic:

 - When you hit enter on the last subtitle and we insert a new one at the end of the list, we remember that change
  - When you click away if that change is the last change, then we undo it
  - If you hit undo, and that change is the last change, then we undo that change only

The main difference is in this scenario:
 - I hit enter to create a new subtitle
 - I type in a bunch of letters, then hit backspace to delete them all
 - I click away

Before, we would delete the subtitle which made some sense.  But then if I hit the undo key, what should happen?  It's really unclear, since the first thing that happens is we cancel the edit, but then that results in a change to remove the subtitle.  That makes the undo stack pretty crazy.

**Comment by PCF-Testing** [comment]
I think this one behaves well now.

**Comment by PCF-Testing** [comment]
Deployed.
