### ISSUE TITLE
Update multiple selects when more than 1 line of items is selected

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3333]
### For changelog:
No changelog entry
====
If you have a multiple select, like the language selector for create requests, and the user selects enough items to overflow a single line, then we should do the following:

 - Hide the overflow
 - Add a link that says "[count] selected" right-aligned inside the field
 - If you click that link, then we expand the selector (all selections shown, searchbox shown, all options shown -- it's as if you simply clicked on the selector)
 - When the selector is expanded, then the overflow should no longer be hidden, and the "[count] selected link should be hidden

https://app.zeplin.io/project/5ac7a5796986566352af25f4/screen/5b636119377ce87e62b70229

**Comment by danantonioreyes** [comment]
My interpretation of the description "if you click that link, then we expand the selector" is expanding the whole field to look like:

![image](https://user-images.githubusercontent.com/1912705/44268698-d80d9c00-a264-11e8-8ada-514e19295bc3.png)

instead of having a panel that contains all the selections appear below the selector as indicated in the zeplin comp. I think the old look is much better for an expanded view

**Comment by danantonioreyes** [comment]
Implemented in https://github.com/pculture/unisubs/tree/gh-unisubs-3333

As discussed with Ben, the selection count indicator is instead displayed inside the field itself. The selection count indicator is not really a link but more of just a label to show how many selections are selected (including the ones that can be seen). You just simply open the selector to see all the current selections.

Can be tested at various places:
http://unisubs.example.com:8000/en/purchase-subtitles/
http://unisubs.example.com:8000/styleguide

**Comment by PCF-Testing** [comment]
I have tried it on both pages (styleguide and Purchase Subtitles), in FF and Chrome, but the multiple select does not behave as specified in zeplin mock-up. A click on "XX selected" does not expand the full list of selected values.

![screenshot from 2018-08-24 03 47 20](https://user-images.githubusercontent.com/288455/44580856-6f388f00-a750-11e8-9052-7867fd06bda2.png)

**Comment by danantonioreyes** [comment]
@bendk and I discussed over dev call that the "n selected" text should be:

1. Just text and not a link
2. Placed inside the selector rather than outside
3. It doesn't really add any functionality since it is just text to indicate how many total selections are currently located

The goal is that the selector still behaves as it used to, i.e. clicking over the "n selected" text should just function as if the text is not there at all--it should expand the whole selector and show the search bar and available options

**Comment by PCF-Testing** [comment]
@danantonioreyes @bendk: I have no objections to the behavior of this element as described above. However, I do see a problem with the way it is already in use on some marketing and application pages, where you have no way of seeing all the selected languages - just the total number:

![screenshot from 2018-08-29 05 37 50](https://user-images.githubusercontent.com/288455/44788131-10a75280-ab4e-11e8-96c4-acc4a6bf866d.png)

Happens on:
- https://amara.org/en/purchase-subtitles/
- https://amara.org/en/recruitment/apply/
- The modals for creating new subtitle requests
- The modal for creating new pro requests

**Comment by danantonioreyes** [comment]
@PCF-Testing when you click on the selector to expand it, it should show all the current selections

**Comment by danantonioreyes** [comment]
Created #3369 to update the behavior of multiple selects

**Comment by PCF-Testing** [comment]
Deployed.
