### ISSUE TITLE
Create workflow diagram element

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3337]
Mockup:

https://app.zeplin.io/project/5ac7a5796986566352af25f4/screen/5b63611956de51ca5193dbd2

Details:
  - The "Complete" section should always take up the right 1/3rd of the width
  - The other 2/3rds should be divided up between:
     - Transcribe/Translate
     - Review (if enabled)
     - Approve (if enabled)
  - For those 3 sections, each should have a width proportional to the amount of days it takes.
  - Those sections can potentially get fairly wide.  If so, left-align the content and place the extra space on the right.

**Comment by danantonioreyes** [comment]
Implementation details:

- the diagram tries to fit the workflow steps (transcribe/translate, review, approve) in the 2/3 space of the container
- each segment of the diagram has a minimum width of 125px (this seems to be the best looking width that can fit the possible texts per segment) with the last segment for displaying COMPLETE has a minimum width of 150px --- this is to handle extreme cases, for example: 1 day translate/transcribe, 999 days review, 1 day approve. The minimum widths are there so that no matter how ridiculous the ratio of the workflow step durations are, each segment will still be displayed somewhat properly. This also means that the COMPLETE segment will get squeezed into just 150px instead of occupying the right-most 1/3 of the container's width
- added icon for the Complete segment since SVG behaves weirdly when I don't add it in (the workflow segments get pushed downward for some reason if the last segment does not have a similarly-sized icon)

**Comment by PCF-Testing** [comment]
With Transcribe / Review / Approve taking equal duration (say, 30 days each), "Complete" section occupies almost half of the width of the diagram:

![screenshot from 2018-09-14 07 52 42](https://user-images.githubusercontent.com/288455/45557841-625d0780-b7f3-11e8-8a6b-ccde4004dc8e.png)

**Comment by danantonioreyes** [comment]
@PCF-Testing @bendk @kslottow 

I'm suggesting instead of having the "Complete" section take over 1/3 of the diagram (when possible), can we just make it always 150px wide? (this is one of the best widths I've come up with while creating the diagram which fits the "COMPLETE" label nicely)

1. The behavior is going to be consistent -- right now for extreme cases (as described above) the COMPELTE section will get squeezed if the ratio's of the first three sections are out of this world
2. There's more room for the visual representation of actual workflow steps -- having more pixels to work with, the ratio of the workflow steps can be better portrayed (imagine dividing a small 8-inch diameter pizza into 6 differently sized portions and then dividing another 15-inch diameter pizza into 6 differently sized portions of same proportions as the one in the smaller pizza--the difference between the portions will be much more obvious in the bigger pizza)

**Comment by danantonioreyes** [comment]
Updated the workflow diagram so that the COMPLETE section is now fixed at the right-most side -- playing around with the ratios in the style guide page should feel more comfortable now and the ratio differences should be more obvious

**Comment by PCF-Testing** [comment]
Hmm... this looks good to me on full screen desktop browser size, but if I resize the browser down to ~800 px width and choose 30-15-5 values, the diagram spills over the edge of the screen and has to be scrolled horizontally. I don't know if we really need to support such small screen widths, but /styleguide/generalLayout mentions 768 px and below, so wanted to make it known.

**Comment by PCF-Testing** [comment]
Looks good now. Thanks for your patience!

**Comment by danantonioreyes** [comment]
PR for this will be created when pculture/amara-enterprise#2050 has been verified

**Comment by danantonioreyes** [comment]
The PR for this is https://github.com/pculture/unisubs/pull/3477 (which is connected to pculture/amara-enterprise#2050)

**Comment by PCF-Testing** [comment]
Deployed.
