### ISSUE TITLE
Update modal styles

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3342]
Make them match the mockup here:

https://app.zeplin.io/project/5ac7a5796986566352af25f4/screen/5b2a93a160a284fd41721eb0

Make sure to update the styles for current modals:
 - Management pages
 - Videos page (add url, etc)

**Comment by bendk** [comment]
Implemented in the gh-3342 branch.

To test you basically need to go through all the modal dialogs on amara and make sure they still work right.

**Comment by PCF-Testing** [comment]
1. The modal style looks great in the mock up, but on the live page the look may be not so great because the dark teal header is positioned against the dark purple background of the announcement banner (if one is visible). This makes the header hard to see:

![screenshot from 2018-09-04 08 34 32](https://user-images.githubusercontent.com/288455/45041702-d80beb00-b01d-11e8-9436-695c51919b5d.png)

2. The UI language selector looks too small compared to the older version. The Transifex link is not visible unless you scroll to the bottom, and the languages are spaced too tight - this modal can easily get messed up when translated.

3. "Change Member's Role" incorrectly shows the member whose role is about to be modified. It is a regression compared to dev.

4. For bulk action modals, the padding between "XX objects selected" and "Apply to all YY objects" is way too large compared to the rest of the modal:

![screenshot from 2018-09-04 08 48 20](https://user-images.githubusercontent.com/288455/45042349-5a48df00-b01f-11e8-859c-cca79bcd8b24.png)

5. For bulk uploading videos from a csv file, the selected file name does not get displayed in the modal after the selection is made.

**Comment by bendk** [comment]
- Made the overlay darker.  Hopefully that should fix the issue with the announcements.
- Fixed the language selector styles

> "Change Member's Role" incorrectly shows the member whose role is about to be modified. It is a regression compared to dev.

This seems like an improvement to me.  Is there a reason not to display the member you you're changing?

> For bulk action modals, the padding between "XX objects selected" and "Apply to all YY objects" is way too large compared to the rest of the modal:

I think this might be because text is confusing.  The "XX objects selected" is the header for the modal.  There's exactly the same spacing as when we display the video title there.  It's not supposed to be directly connected to the "Select all XX results" field.

Could we fix this one in another issue?  I made #3385 for that

**Comment by bendk** [comment]
> For bulk uploading videos from a csv file, the selected file name does not get displayed in the modal after the selection is made.

I made #3370 for this one.

**Comment by PCF-Testing** [comment]
- [ ] If the link to the Transifex translation project still does not fit into the visible part of the UI language selector, how about placing it above the list of languages? If the user can see her language in the visible part (which is very likely because most languages are exposed), I don't see why she would scroll down to the bottom of the modal to discover the link.

- [ ] On Members page, Add/Invite Members modal has [x] button along with Cancel button. I think it should only have Cancel. Also, if Cancel is clicked, the modal displays an error message saying that the usernames cannot be left blank.

- [ ] 
> This seems like an improvement to me. Is there a reason not to display the member you you're changing?

Of course it should be an improvement, but unfortunately it does so incorrectly. Instead of displaying the target username that is about to be modified, it displays the username of the currently signed in user:

![screenshot from 2018-09-06 06 01 56](https://user-images.githubusercontent.com/288455/45159328-53df7200-b19b-11e8-8086-e5fe4285a66a.png)

- [ ] "Change Role" modal is broken when "Project/Language Manager" role is selected - the drop-downs for choosing the project and language are missing.

**Comment by bendk** [comment]
Oops, I forgot about the transifex link.  I fixed that by adding max-height and scrollbars to the language list.

**Comment by PCF-Testing** [comment]
Verified.

**Comment by bendk** [comment]
Changelog info:
  - Updated/improved modal dialog style

**Comment by bendk** [comment]
This got merged to dev a while back.

**Comment by PCF-Testing** [comment]
Deployed.
