### ISSUE TITLE
Experimental editor: at typing stage, the first subtitle gets permanently stuck in the overlay

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3345]
Observed on the experimental-editor branch.

As you start a new transcript and start typing the dialogue in the video, the first subtitle gets displayed in the overlay on the video screen. As you keep typing and add more subtitles to the set, they do not get displayed - instead, the first subtitle remains permanently stuck on the screen.

**Comment by bendk** [comment]
This is because we changed the logic on what to display in the video player.  We now display the subtitle at the red line in the timeline.  The timeline isn't displayed, but if you did show subtitle, you would see the first subtitle displayed there, since it's the first unsynced subtitle.

This is very unintuitive.  I'm going to make it so we only show synced subtitles in the video player, never unsynced ones.

**Comment by PCF-Testing** [comment]
I am not super happy about this solution, since as you type, you cannot see what the text would look like on the screen and change the position, if needed. You'd need to do all the positioning at syncing or review step, for each subtitle individually (while at the typing step, we kept the subtitle positioning as the default for the next subtitle). However, I am going to close this ticket and let the beta testers have their say on it.
