### ISSUE TITLE
Implement new dropdown styles

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3362]
Here's a comp that lists them: https://app.zeplin.io/project/5ac7a5796986566352af25f4/screen/5b644bd579bf647e14cc7b4e

We should make a few changes from the comp:
 - Larger font size
 - Don't make non-highlighted items lighter color, that's hard to read and we want to use it to indicate disabled menu items

**Comment by bendk** [comment]
Implemented in the 3362 branch.

Some things to test:
  - The download menu works on the subtitles page
  - The user menu still works
  - Test this on old, new, and futureui styled pages

**Comment by PCF-Testing** [comment]
- [ ] The username in the top right corner is now displayed in all uppercase letters. Should be case-sensitive, so that the user knows their username and can enter it correctly on the Sign In page.

- [ ] The user drop-down menu does not function on the futureui and marketing pages (except the home page).

**Comment by bendk** [comment]
I fixed the uppercase issue.

I was able to get it to work on the other pages.  You might need to run `dev manage clear_cache` to update the HTML before testing them.

**Comment by PCF-Testing** [comment]
The user menu issue is gone.

With the new font size, text on marketing pages looks and feels too condensed - I like the version that is currently in production better. An example where the new layout looks too condensed:

![screenshot from 2018-08-27 04 56 18](https://user-images.githubusercontent.com/288455/44658920-5b429680-a9b7-11e8-8f06-330a6b009a34.png)

I don't understand the "keyboard shortcuts" part, what is that about?

**Comment by bendk** [comment]
> I don't understand the "keyboard shortcuts" part, what is that about?

Check out the keyboard shortcuts here:

https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html

**Comment by bendk** [comment]
Font size should be fixed now.

**Comment by PCF-Testing** [comment]
Confirming that the font size is fixed.

Regarding keystrokes, I am observing the following:
- On old-style pages, the user menu does not respond to keystrokes. Pressing Arrow Down key scrolls the page down instead of moving the focus in the menu
- On the marketing and futureui pages, you need to click the username AND press Arrow Down key to start navigating the menu with the use of keys
- It takes several ESC keystrokes to close the menu - usually 2 if no item has focus and 3 if there is an item in focus
- Once you start navigation in the user menu, if you click outside of it, it remains open and becomes unresponsive - pressing keys no longer takes effect

This feels a bit awkward and counterintuitive to me. I would expect the keys to work as soon as the menu is open, without having to press Arrow Down first, and the first stroke on ESC to close the menu at once.

**Comment by PCF-Testing** [comment]
Also hit https://github.com/pculture/amara-enterprise/issues/2072 on this branch. The problem does not happen on dev.amara.org.

**Comment by bendk** [comment]
- I only implemented the keyboard bindings on futureui, so just ignore old style pages
- Made it so you can use the alphabet keys to navigate after clicking the menu button
- Fixed the ESC behavior
- If you click outside the menu, then some other element has focus.  So the keyboard commands shouldn't go to the menu by design.  I think this is what most people who use the keyboard will expect.

**Comment by PCF-Testing** [comment]
Works great now.

One thing I could still wish for is having the currently selected menu item in a contrast colour, such as purple or teal, because snow against the cream background is hard to see, especially at angles (e.g. in the lower part of the screen).  No pressure, just a suggestion.

Marking as Needs PR.

**Comment by danantonioreyes** [comment]
This will be merged in when PR #3386 gets merged -- this effectively means I'm also reviewing this one

**Comment by bendk** [comment]
Changelog Info:
  - Improved dropdown menus
    - Cleaned up the look
    - Added keyboard accessibility (ARIA guidelines)

**Comment by PCF-Testing** [comment]
Deployed.
