### ISSUE TITLE
Experimental editor: allow users to switch steps by clicking on links

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3375]
We should allow users to click on the "Type what you hear", "Sync Timing", and "Review and Complete"  headers to change their steps.

 - This allows users to go to previous steps
 - It also allows users to skip forward multiple steps if it's allowed
 - The links should be disabled if the user can't change to the new step -- for example, the review link should be disabled unless there are completed subtitles.

**Comment by PCF-Testing** [comment]
I think I like this solution, and I would not worry too much about the reviewers or approvers not being able to restart from square one because they are not supposed to do that - they can make some edits, even re-sync if needed, but if the subtitles are way below the notch and should be re-done, they should just send them back (and, possibly, re-assign).

One thing I think might be difficult for users is that these sections are not displayed as clickable items, except for the cursor change on mouseover. By contrast, other links in the progress panel ("Subtitles cannot be blank", "Timing error in subtitle", "Edit title and description") and CTA buttons ("Yes, start syncing", "Start review", "Publish") are very visible and easy to identify. Could the section titles be at least underlined when they are clickable?

**Comment by bendk** [comment]
The reason I didn't make them underlined is that it feels like it would add too much visible clutter.  How about we change the color to blue on hover?  I think that wanting to move back stages is pretty rare, so we den't need to advertise it so much.

**Comment by PCF-Testing** [comment]
Verified the fix for the translation mode.

OK, let's make the links teal on mouseover. I suspect the use case might not be so rare after all, especially for novice users, and if the users do not get enough visual aid to figure out the solution on their own, it would mean increased workload on our support.

**Comment by bendk** [comment]
I changed the color to "lighter-blue".  It's kind of close to teal.  There's another issue to rework the colors, so I don't want to put too much time into making it perfect right now.  I think we should definitely fix this and some other colors before we publicly announce the experimental editor though.

**Comment by bendk** [comment]
I thought the idea was to change the style on mouseover.  What would you suggest as an alternative?

**Comment by bendk** [comment]
Pretty sure we agreed to keep this how it is for now, and rework it later.

**Comment by PCF-Testing** [comment]
Moving to Holding.

**Comment by PCF-Testing** [comment]
This bit does not work for me on dev: https://dev.amara.org/en/subtitles/editor/TdXOHOy2TaQI/en/?experimental

**Comment by bendk** [comment]
Should be fixed now.

**Comment by PCF-Testing** [comment]
Deployed.
