### ISSUE TITLE
Better handling of keyboard focus with  text input filter

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3425]
- Open the activity page
- Open the filters menu and select "Video"
- Type something in
- Press enter

- Enter should cause the current text to be added to the filter.
  - If there's no text in the input, then enter should do nothing.
- Also, escape should close the dialog.

**Comment by Rachel36** [comment]
@bendk First of all, I love this.  I'm a shortcuts/keyboard kind of person and it irks me when search bars don't bend to my will. Second, here's what I've come across in testing:

- [ ] If I have more than one word or a symbol entered in the filters menu, no results pull (at times).  For example, I have a video entitled, "The best stats you've ever seen."  If I typed in "stats" the filtered results worked correctly.  However, if I typed in "the best stats", no results pulled. (see pics below).  However, I will note that this behavior is inconsistent which is odd. Sometimes it worked correctly, and then other times it didn't, as you can see in my screen shots. I had a hard time trying to pin down what I might be doing to cause it to behave differently. 

- [ ] Does this ticket only specifically apply to the "Video" filter?  I ask because the other filters (for example, "Type") don't seem to function the same way. Escape did not close the dialog box for type, video language, and subtitle language. 

- [ ] The text I entered in the search bar did not clear out after clearing the filter. For example, I had applied the word "stats" as a filter.  After I cleared the filter, and then opened the dialog box up again, the word "stats" still appeared in the text bar. 

![image](https://user-images.githubusercontent.com/42118332/46826978-0edfca00-cd5d-11e8-9ea7-73662f5cb8b6.png)

![image](https://user-images.githubusercontent.com/42118332/46827018-26b74e00-cd5d-11e8-8232-1985aeef7b82.png)

**Comment by bendk** [comment]
> ￼If I have more than one word or a symbol entered in the filters menu, no results pull (at times).  For example, I have a video entitled, "The best stats you've ever seen."  If I typed in "stats" the filtered results worked correctly.  However, if I typed in "the best stats", no results pulled. (see pics below).  However, I will note that this behavior is inconsistent which is odd. Sometimes it worked correctly, and then other times it didn't, as you can see in my screen shots. I had a hard time trying to pin down what I might be doing to cause it to behave differently.

That seems like a bug with video search in general.  I'm guessing it's because "the" is a common word so there's some extra weirdness around it.  Can you open up another issue to deal with this?


> ￼Does this ticket only specifically apply to the "Video" filter?  I ask because the other filters (for example, "Type") don't seem to function the same way. Escape did not close the dialog box for type, video language, and subtitle language.

It applies to all filters that use a textbox.  As far as I know that's only the video filter.  Those other filters use a select which has its own keyboard handling.
￼
> The text I entered in the search bar did not clear out after clearing the filter. For example, I had applied the word "stats" as a filter.  After I cleared the filter, and then opened the dialog box up again, the word "stats" still appeared in the text bar.

I think this is correct, since the "stats" filter is still active on the page.  I'm not totally sure about this though, do you think we should change it?

**Comment by Rachel36** [comment]
> 
> That seems like a bug with video search in general. I'm guessing it's because "the" is a common word so there's some extra weirdness around it. Can you open up another issue to deal with this?

I've created issue #3463  

> 
> > The text I entered in the search bar did not clear out after clearing the filter. For example, I had applied the word "stats" as a filter.  After I cleared the filter, and then opened the dialog box up again, the word "stats" still appeared in the text bar.
> 
> I think this is correct, since the "stats" filter is still active on the page. I'm not totally sure about this though, do you think we should change it?

Does a filter remain active on the page even after all filters are cleared?  I'm seeing the word still appear in the dialog box even after clearing filters, so it kind of confused me.  I assumed the previous text filters were no longer relevant.

**Comment by bendk** [comment]
If you clear the filter, then it shouldn't be active anymore.  I'm having trouble reproducing this one.  Can you give me complete steps to see it?

**Comment by Rachel36** [comment]
Hi @bendk! I'm getting an error on the activity page during my testing this evening. 

![image](https://user-images.githubusercontent.com/42118332/47053570-3bd41880-d173-11e8-8635-0c40401625a6.png)

**Comment by bendk** [comment]
@Rachel36 Can you try dev manage migrate?  That might fix the issue

If not, I'll need to merge some code from dev into the branch

**Comment by Rachel36** [comment]
@bendk Thank you! Dev manage migrate worked. I'm unable to reproduce the issue I was having before with words remaining in the dialog box. (Cleared my cache and cookies?  Maybe that fixed it - not sure).  In any case, 3425 has been verified!

**Comment by PCF-Testing** [comment]
Deployed.
