### ISSUE TITLE
Add the ability to undo / reset changes

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#395]
Add an undo shortcut to the editor to allow users to reset changes. 

Previous work on undo:
#1145 pull request for Gh branch 395 - this is marked as merged.
#1043

**Comment by bendk** [comment]
Couple notes for this one:

- Almost all actions should now be undoable, the only ones that aren't are:
    - Changing the title/description
    - Actions that involve reloading the subtitles (revert and upload)
- All other actions should be undoable, the main thing to test is that things get grouped correctly.  For example, if I do clear all timings, then undo, that should restore all the timings, not just the timing for the last subtitle
- I removed confirm dialogs from some actions since you can now undo them: clear text, clear timings, and copy timings

**Comment by bendk** [comment]
Just pushed the gh-395 branch for this.

**Comment by PCF-Testing** [comment]
> Undo/redo are located in the wrench menu

This does not happen for me. The shortcuts are listed in the list of available shortcuts, but there is no menu item for undo / redo.

> I removed confirm dialogs from some actions since you can now undo them: clear text, clear timings, and copy timings

I agree that it is OK for clearing text and timing, but the confirmation dialog for copying timing had some valuable information on how this feature works. This info is not 100% intuitive and not so easy to find elsewhere, so maybe it would be better to keep it.

- [ ] How is redo supposed to work? For example, I clear all text, then press CTRL+Z to undo this action (which succeeds), then CTRL + SHIFT + Z to redo - and this last keystroke does nothing. Is this as expected?

**Comment by PCF-Testing** [comment]
Hmm, actually I do see Undo menu item, but it only appears in the menu after some undo-able actions. I am afraid this way it might be harder to discover. How about disabling it instead of completely hiding when there is nothing to undo?

**Comment by PCF-Testing** [comment]
Regarding the glyphicons for the new menu items, I found the following matches that could be suitable:

1) https://github.com/pculture/amara-assets-legacy/blob/master/glyphicons_all/glyphicons/png/glyphicons_365_restart.png for undo and 
https://github.com/pculture/amara-assets-legacy/blob/master/glyphicons_all/glyphicons/png/glyphicons_085_repeat.png for redo,
or
2) https://github.com/pculture/amara-assets-legacy/blob/master/glyphicons_all/glyphicons/png/glyphicons_435_undo.png for undo and
https://github.com/pculture/amara-assets-legacy/blob/master/glyphicons_all/glyphicons/png/glyphicons_434_redo.png for redo.

**Comment by PCF-Testing** [comment]
There is also some weirdness in the timeline when I append a new subtitle to a synced set and then start undoing things:
1. Upload (or type and sync) some subtitles.
2. Click +New subtitle at the bottom.
3. Type some text in the new cell.
4. In the last timed subtitle, select Seek to Subtitle.
5. Press TAB to play and then Arrow Down to set the start and end times for the new subtitle.
6. Press TAB to pause and apply Undo to the last action (change time). The subtitle is now displayed both as being currently synced and on-deck:

![screenshot from 2018-05-15 03 12 58](https://user-images.githubusercontent.com/288455/40051135-8a1796b0-57ee-11e8-9802-1d53e6f624b4.png)

Also, I am seeing that editing the video title and description is not undoable at this time. Is it something hard to do?

**Comment by bendk** [comment]
- Fixed it so when you do insert before, we never extend the previous subtitle duration
- I'm not sure what the tooltip text should be, I think undo/redo is pretty self explanatory.  Is there something you'd suggest?
- Updated the keyboard shortcuts to:
   - Undo: Ctrl-Z or Command-Z
   - Redo: Ctrl-Y (non-mac) and Command-Shift-Z (mac)
- Fixed the weird issue with the displaying unsynced subtitles

**Comment by PCF-Testing** [comment]
> I'm not sure what the tooltip text should be, I think undo/redo is pretty self explanatory. Is there something you'd suggest?

They are all identical to the menu commands. Having a tooltip identical to the name of the menu command should be perfect, I think.

> Updated the keyboard shortcuts

The list of shortcuts still has the old values:

![screenshot from 2018-05-16 02 56 03](https://user-images.githubusercontent.com/288455/40110566-26ca8690-58b5-11e8-88ab-399f11a95ab8.png)

> Fixed it so when you do insert before, we never extend the previous subtitle duration

Below is what the current insertion behavior looks like, does this sound ok?
`1. Insert subtitle before subtitle 1 when there is no gap (subtitle 1 starts at 00:00:00.000).
1A. Subtitle 1 is longer than 6 sec: subtitle 0 is 3 sec long, subtitle 1 gets the remaining time.
1B. Subtitle 1 is 6 sec or less: subtitle 0 and subtitle 1 are split equally.

2. Insert subtitle before subtitle 1 when there is a gap before subtitle 1.
2A. The gap is longer than 3 seconds: subtitle 0 is 3 sec long, placed into the middle of the gap.
2B. The gap is 3 seconds long, subtitle 1 has any duration: subtitle 0 becomes 00:00:00.000-->00:00:03.000
2C. The gap is shorter than 3 sec, subtitle 1 and the gap together are longer than 6 sec: subtitle 0 becomes 00:00:00.000-->00:00:03.000, start time for subtitle 1 moves to 00:00:03.000.
2D. The gap is shorter than 3 sec, subtitle 1 is longer than the gap: subtitle 0 and subtitle 1 take the space of the gap and subtitle 1 and split it in equal shares, start time for subtitle 1 moves, end time doesn't.
2E. The gap is shorter than 3 sec, subtitle 1 is shorter than the gap: subtitle 0 fills the entire gap, subtitle 1 doesn't change.

3. Insert subtitles between two adjacent subtitles.
The first of the two adjacent subtitles is split into 2 equal parts, the second subtitle does not change.

4.Insert subtitles between two subtitles separated by a gap.
4A. The gap is longer than 3 seconds: the middle subtitle is 3 sec long, placed into the middle of the gap.
4B. The gap is 3 seconds long: the middle subtitle fills the entire gap.
4C. The gap is shorter than 3 seconds and shorter than the previous subtitle: the space taken by the previous subtitle and the gap is split equally between the previous subtitle and the middle subtitle. End time for the previous subtitle changes.
4D. The gap is shorter than 3 seconds but longer than the previous subtitle: the middle subtitle fills the entire gap, the previous subtitle does not change.`

Do we really need to insist on inserting 3 sec long subtitles whenever possible? If the cutoff is made at 1 sec instead of 3, I think the number of cases when the timing for the adjacent subtitles have to shift would reduce a lot. At the same time, 1 second long subtitle is still very easy to see and re-sync. What do you think?

**Comment by bendk** [comment]
- Updated the keyboard shortcut dialog
- Switched to making 1 second long subtitles for insert before.  I agree with your logic
- I didn't add the tooltip, it just seems very strange to me that the text would say the same thing as the menu item.  I think it should add something different or there's no point.  Maybe we could talk about this more alongside the layout change, since there's going to be more stuff in menus at that point.

**Comment by bendk** [comment]
I'm pretty sure that last issue was caused by the CSRF cookie change to HTTP-only.  I'm going to merge dev into the branch, I think that should fix it.

**Comment by PCF-Testing** [comment]
Confirming that te issue with regaining the lock is gone now.

A weird thing happens if I paste a chunk of text into a subtitle (e.g. a 4 lines long fragment of song lyrics) and then try to split it into individual lines / subtitles:
- I position the cursor in the middle (at the beginning of line 3) and press CTRL+ENTER
- The first 2 lines remain in the subtitle cell, the second 2 lines disappear
- I click Undo, then the whole text disappears

**Comment by bendk** [comment]
I was able to reproduce the issue with undo, but not the issue where the second 2 lines disappear.  Maybe my fix will fix that one too though.

If you still see a bug, can you give me some more details about the state of the subtitle list before the operation?  How many total subtitles, are they synced?  etc.

**Comment by PCF-Testing** [comment]
Split-off subtitles still keep disappearing on the latest version of the branch. This is 100% reproducible with an untimed subtitle of any length:
1. Submit a video (it should have no subtitles imported from external sites).
2. Start a transcription.
3. In the editor, type or paste some text into the cell in the typing panel. Do not time it.
4. Click in the middle of the text and press CTRL+ENTER. 
This adds a new subtitle cell and removes the text after the cursor from the original cell, but that text disappears from the editor completely.
(Undo does work for this case now though.)

**Comment by bendk** [comment]
Just fixed that one.

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed.
