### ISSUE TITLE
Fix youtube language encoding  zh-TW

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#452]
Test video http://www.youtube.com/watch?v=l8_fZPHasdo

**Comment by PCF-Testing** [comment]
Still a problem:
https://www.youtube.com/watch?v=i2pmnXvwCzw
http://ted-support.amara.org/helpdesk/tickets/78467

**Comment by bendk** [comment]
This should be a realtively easy fix if I can get a list of language code translations -- which amara language codes are not working and what are the corresponding youtube language codes?

**Comment by PCF-Testing** [comment]
@bendk: subtitle import from YT breaks on the languages whose YT codes include locales (es-ES, pt-PT, zh-TW, en-CA, etc.).

You can test with the following videos: 
https://www.youtube.com/watch?v=IWpjQVcaYEQ
https://www.youtube.com/watch?v=3_petnJUYqk

**Comment by jdragojevic** [comment]
Added the videos locally.    Looks like we have a few different issues going on:

- [ ] 1. if we hit an issue while importing, we stop at that language and don't import the rest
- [ ] 2. Issue with 'no' being not found
- [ ] 3. the for BCP47 error for languages that are not found. 

I imagine we'll need to fix with the switchover to the youtube v3 api, and prioritize based on whether or not youtube will continue to allow subtitles to be pulled via the api.

Testing with: http://www.youtube.com/watch?v=3_petnJUYqk

I got an error in the logs when it was trying to retrieve norweigan, 'no' and afterwards no further languages were retrieved from youtube.
```
worker_1 | [2015-03-26 06:53:55,564: DEBUG/MainProcess] "GET /api/timedtext?lang=mr&fmt=srt&v=3_petnJUYqk ('HTTP/1.1',)" 200 None
worker_1 | [2015-03-26 06:53:55,927: ERROR/MainProcess] Task externalsites.tasks.fetch_subs[cb3aed18-f37e-492e-9b5b-5d3a699c3160] raised exception: KeyError('no',)
worker_1 | Traceback (most recent call last):
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 224, in trace_task
worker_1 |     R = retval = fun(*args, **kwargs)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 403, in __protected_call__
worker_1 |     return self.run(*args, **kwargs)
worker_1 |   File "/opt/apps/unisubs/apps/externalsites/tasks.py", line 134, in fetch_subs
worker_1 |     subfetch.fetch_subs(VideoUrl.objects.get(id=video_url_id))
worker_1 |   File "/opt/apps/unisubs/apps/externalsites/subfetch.py", line 38, in fetch_subs
worker_1 |     fetch_subs_youtube(video_url)
worker_1 |   File "/opt/apps/unisubs/apps/externalsites/subfetch.py", line 50, in fetch_subs_youtube
worker_1 |     language_code = LanguageCode(bcp47_lc, 'bcp47').encode('unisubs')
worker_1 |   File "/opt/apps/unisubs/unilangs/unilangs.py", line 1200, in encode
worker_1 |     return FROM_INTERNAL[standard.lower()][self._code]
worker_1 | KeyError: 'no'
worker_1 | [2015-03-26 06:53:58,264: INFO/Beat] Scheduler: Sending due task gauge_billing_records (videos.tasks.gauge_billing_records)

```

Testing with: https://www.youtube.com/watch?v=IWpjQVcaYEQ
It his the error below for chinese traditional zh-TW and then failed to import the rest of the languages in the list.
```
worker_1 | [2015-03-26 06:57:34,385: DEBUG/MainProcess] "GET /api/timedtext?lang=bg&fmt=srt&v=IWpjQVcaYEQ ('HTTP/1.1',)" 200 None
worker_1 | [2015-03-26 06:57:36,011: ERROR/MainProcess] Task externalsites.tasks.fetch_subs[67c2e167-e67e-42fa-91e8-34314dd1664e] raised exception: KeyError(u"Could not find Unilangs language for BCP47 language 'zh', region 'tw', script 'None'",)
worker_1 | Traceback (most recent call last):
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 224, in trace_task
worker_1 |     R = retval = fun(*args, **kwargs)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 403, in __protected_call__
worker_1 |     return self.run(*args, **kwargs)
worker_1 |   File "/opt/apps/unisubs/apps/externalsites/tasks.py", line 134, in fetch_subs
worker_1 |     subfetch.fetch_subs(VideoUrl.objects.get(id=video_url_id))
worker_1 |   File "/opt/apps/unisubs/apps/externalsites/subfetch.py", line 38, in fetch_subs
worker_1 |     fetch_subs_youtube(video_url)
worker_1 |   File "/opt/apps/unisubs/apps/externalsites/subfetch.py", line 50, in fetch_subs_youtube
worker_1 |     language_code = LanguageCode(bcp47_lc, 'bcp47').encode('unisubs')
worker_1 |   File "/opt/apps/unisubs/unilangs/unilangs.py", line 1190, in __init__
worker_1 |     self._code = standard_dict[language_code]
worker_1 |   File "/opt/apps/unisubs/unilangs/bcp47/converter.py", line 327, in __getitem__
worker_1 |     return self._lookup_dict.lookup(language, region, script)
worker_1 |   File "/opt/apps/unisubs/unilangs/bcp47/converter.py", line 25, in lookup
worker_1 |     % (language, region, script))
worker_1 | KeyError: u"Could not find Unilangs language for BCP47 language 'zh', region 'tw', script 'None'"
worker_1 | [2015-03-26 06:57:39,188: DEBUG/Beat] Celerybeat: Waking up in 5.00 seconds.

```

**Comment by bendk** [comment]
@PCF-Testing I don't think it's simply a matter of locales, I think some language codes with locales will work and some won't.

This is all because we try to map youtube's language codes to our own internal codes.  I don't really love this system in general, see #1813.  I wonder what would happen if we decided not to map the language codes and instead simply used youtube's codes directly?  I'm going to make a branch to test this.

The thing to test is if there are some UI components that won't work with a language code like "no" or "zh-tw", which isn't one of the default amara language codes.  One that I know of is the task creation form are there others?

**Comment by bendk** [comment]
Just pushed a commit to test out.  After that change we just use youtube's language code for our languages.  Again, the question is what parts of our UI break because of this change?

**Comment by jdragojevic** [comment]
@bendk - got an error when trying to sync-back non-mapped language codes to youtube.

```
local variable 'language_code' referenced before assignment
```

for those extra codes like es-es.

**Comment by jdragojevic** [comment]
@PCF-Testing (Margarita) can you think of any more things in the UI that may be affected by allowing in the language codes like 'es-es' without mapping?

**Comment by bendk** [comment]
I think that issue should be fixed, but now there are a couple of things we need to consider with syncing subs back to youtube:

* We always use lower-case language codes, but youtube uses upper case for region (like bcp-47 suggests).  I think that language codes should be case-insensitive, but we need to test if they accept our language codes or not.  Any language code with a region should be a good test (pt-BR).
* Before we would map some of the language codes.  AFter the change we don't anymore.  Is this going to be an issue for youtube content owners since it means that we will create 2 tracks?  Not sure how to work around this issue.

**Comment by jdragojevic** [comment]
@bendk:  

```
Attaching to unisubs_app_1
app_1 | INFO 2015-03-31 12:50:30,694 base 1 139949167904576 Raven is not configured (logging is disabled). Please see the documentation for more information.
app_1 | Traceback (most recent call last):
app_1 |   File "manage.py", line 37, in <module>
app_1 |     startup.startup()
app_1 |   File "/opt/apps/unisubs/startup.py", line 68, in startup
app_1 |     run_startup_modules()
app_1 |   File "/opt/apps/unisubs/startup.py", line 59, in run_startup_modules
app_1 |     __import__('%s.startup' % app)
app_1 |   File "/opt/apps/unisubs/apps/externalsites/startup.py", line 19, in <module>
app_1 |     import externalsites.signalhandlers
app_1 |   File "/opt/apps/unisubs/apps/externalsites/signalhandlers.py", line 24, in <module>
app_1 |     from externalsites import credit
app_1 |   File "/opt/apps/unisubs/apps/externalsites/credit.py", line 28, in <module>
app_1 |     from externalsites import models
app_1 |   File "/opt/apps/unisubs/apps/externalsites/models.py", line 36, in <module>
app_1 |     from externalsites import syncing
app_1 |   File "/opt/apps/unisubs/apps/externalsites/syncing/__init__.py", line 23, in <module>
app_1 |     from . import youtube
app_1 |   File "/opt/apps/unisubs/apps/externalsites/syncing/youtube.py", line 114
app_1 |     language_code = subtitle_version.subtitle_language.language_code)
app_1 |                                                                     ^
app_1 | SyntaxError: invalid syntax

```

**Comment by bendk** [comment]
So the last part about this is how we handle the existing videos.  Since we are now switching the language code that we're syncing to, there are a couple of potential issues that we need to work through.  For example, before "es" was synced to "es-ES".  After this change we will just sync it as "es".  There are two issues that I can think of:

Existing videos and new videos will have different language codes synced.  So my video that I added subtitles to last year will have the subtitle track as "Spanish (Spain)", but the new ones will be "Spanish".  I think we will just have to live with this one.  The only work around I can see is to try to re-sync all subtitle sets, and that will probably fail in some cases if our access tokens have expired.

If new subtitles get added to existing videos we could have duplicate tracks, sync we could have synced the subtitles before to "es-ES" and now we're syncing to "es".  I think we can mostly handle this one with the help of the sync history.  It's annoying that we don't have sync history for all sync attempts since it was added fairly recently, but we can work around that.

First off, we keep around the youtube language mapping and use it to figure out what the old language code would have been.  There are 3 cases and only 1 needs special handling:
* If the old language code and the new language code are the same, then we don't need to do anything special
* If the old mapping would throw an exception, then we don't need to do anything special.
* If the old language code and the new language code are different, and there's a youtube caption track for the old language code, then we need to figure out if we should delete the youtube track for the old language code.  Here's how we do it:
  * We only delete the track if there is a previous subtitle version.
  * We add a field to sync history called new_language_logic.  We set that to False for all existing sync history objects, and True for all the new ones.
  * If there is a sync history with new_language_logic for the new language code, then we don't delete the old one, since that means we already went through this process.
  * If there is a sync history with new_language_logic for the old language code, then we don't delete the old one.  This covers a corner case where the user added subtitles for both "es" and "es-ES", which is possible via the API.
  * Otherwise we delete the old track.

There is some possibility that we're deleting a track that amara didn't sync, but I don't think that's too big of an issue.  After all, with the old logic, we would have synced to that language code anyways, which would overwrite the subtitles.

@jdragojevic @PCF-Testing does this logic seem sound to you?

**Comment by PCF-Testing** [comment]
Makes sense to me, except that I do not think that we actually need to re-sync all the previously synced subtitle sets - why not apply the change only to the subtitles added in the future. And perhaps it would be safer not to delete duplicate subtitle tracks with a locality specified - maybe just let them be and let the video owner remove them if they get too annoying. After all, nobody seems to mind ASR subtitles remaining in the menu together with man-made subtitles - so I'd just leave the obsolete subtitles be.

**Comment by bendk** [comment]
@PCF-Testing that sounds fine to me, the next step is creating a PR for this one to staging.  Do you want to handle that one?

**Comment by PCF-Testing** [comment]
I keep getting 'backendError' when trying to sync Montenegrin to YouTube on different videos on staging:
http://staging.amara.org/en/videos/ldF5bO9mTZzS/srp/1038055/?tab=sync-history
http://staging.amara.org/en/videos/OV19esW5TP5v/srp/1038041/?tab=sync-history

**Comment by bendk** [comment]
I think this is just because youtube doesn't support that particular language code.  Maybe they support the language with a different code.  In any case, we should open a new ticket for that one.

**Comment by bendk** [comment]
This one got deployed today, we can finally close it.
