### ISSUE TITLE
Appended lines are hard to sync

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#476]
As a user adds or appends lines through the new editor and types the text, there is no easy way to get these new lines synced:
- Pressing Enter appends a new line and prompts to type text. The only way to stop appending is to delete the last appended line
- Pressing Shift+Space plays/stops the video
- Pressing Arrow up/down for syncing takes no effect

Expected:
- the bubble for a new unsynced line should be displayed on the timeline right after the previous bubble (as in the legacy editor)
- It should be grayed out until the start time is set (as in the legacy editor)
- There should be a key combination available for syncing new lines on the fly, as the user plays the video (worked in the legacy editor)

**Comment by kslottow** [comment]
Looks like this issue has been resolved.  @PCF-Testing okay to close this one?

Current behavior:
- the bubble for a new unsynced line is displayed on the timeline as soon as a subtitle is appended.
It is yellow (matching the selected subtitle) until subtitle is saved (press enter).
- appended subtitle can be synced by using the down arrow key.

**Comment by PCF-Testing** [comment]
Yes, I think this can be closed, since in syncing mode you can only add one subtitle at a time - pressing Enter does not create a new subtitle cell anymore, it only happens in the typing mode. Therefore, in syncing mode it is reasonably easy to type a new subtitle at the end of the set, start playing the video, and  sync the new subtitle. Looks good enough to me.

Marking as closed.
