### ISSUE TITLE
Subtitling programming strings results in underlined text instead of underscores

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#583]
User brought this to our attention: 

When subtitling Khan Academy courses with programming, the underscore is required, but not as underline text, but as an underscore. Ex. http://www.khanacademy.org/science/computer-science/v/fun-with-strings  
If the string in subtitle contains two or more underscore characters, the string gets underlined which is not the desired effect.

Might be good to see what other programming might not result with other markup such as **bold** and *italic*.

**Comment by darren-bridenbeck** [comment]
This issue is now affecting Autodesk, Udacity and AOD pretty regularly. If we had to choose a feature -- using underscores or using underlined subtitles, I would agree with Claude for disabling our feature for underlining subtitles, and enable underscores.

**Comment by PCF-Testing** [comment]
What exactly compatibility issues are caused by using Unicode character U+FF3F (＿) instead of the regular underscore?

**Comment by franontanaya** [comment]
Exporting basic English subtitles to EIA-608 specs, which have limited character sets. The tooling out there will error/skip on invalid characters. Some like MacCaption has a conversion tool to fix invalids before exporting, but it's basically to turn fancy quotes into straight quotes.

The main issue though is that captioners struggle entering that character, and it looks "defective" on screen. See: get_special_chars vs get＿special＿chars. It's also an issue if text is obtained from a source (from a transcript, or converted from some existing captions) rather than creating it from scratch.

I haven't come across any intended use of underline on Amara yet. There may be already some tracks using FF3F as a workaround, so I wouldn't switch that one to underline.

We could query on a snapshot of the DB and find out how many tracks are currently being rendered with underlining and get a feeling of how many legitimate uses are there, but it'll likely be 99% cases where they just wanted to display two underscores in the same caption.

We could make underscores stop converting to underlines after a cutoff date, if we don't want to alter the behaviour for existing tracks, but even if we didn't, switching from supporting users that didn't expect underline (and we don't have a clean workaround for them) to users that expected it (and we can at least instruct to remove the now displaying underscores) sounds a lot simpler.

**Comment by syl22-00** [comment]
As discussed and suggested, underline formatting was just taken out. If needed, we could adjust the formating syntax to allow underlines and underscores, such as:
* Escaping `\_` for underscores.
* Double underscores for underline `__underlined text__`
* More stricness on where underscore should go to underline: `_underlined_text_` vs. `_not_underlined_text`

**Comment by syl22-00** [comment]
So to be more clear:

* Newly created subtitles just consider underscores as any other character, no underline is be created.
* Existing subtitles are left and appear unchanged
* If an existing subtitle language is open in the editor, subtitles will appear without underlines, just raw underscores characters as they were originally entered. If saved, underlines will be gone, even for the open subtitles that were not modified.

At least no change should be made to subtitles without user not seeing it before publishing.

**Comment by syl22-00** [comment]
For that ticket, I am not sure if there is something to be done. Right now underscores do not underline text. Do we still want a way to add underline while keeping underscores displayed as is.

**Comment by bendk** [comment]
I think if we don't treat underscores specially that's great and this ticket can be closed.    We could implement the double underscore behavior, but I haven't heard any user requests for it so I would just not touch things.

**Comment by deanjansen** [comment]
+1 – I haven't heard any requests for it either
