### ISSUE TITLE
Implement auto-pause feature when in typing mode

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#784]
The legacy editor enabled users to make automatic pauses as they were typing subtitles.

![screen shot 2013-07-26 at 12 40 49 pm](https://f.cloud.github.com/assets/299270/861954/e678466e-f5df-11e2-808e-02b7e808f0dc.png)

The new editor does not have this feature yet. 

Enable users to opt for auto-pausing the video at regular intervals or when typing gets too intensive.

**Comment by deanjansen** [comment]
Nate – this is a consolidation of the key parts of the ticket. Ben started to work on this feature, but other priorities prevailed. It's probably simplest for you to start from scratch (unless you prefer otherwise). I've created a digest of key comments/insights/guidelines.

**Ben says:** Okay, here's how I believe auto-pause works:

  * If the user continuously types for 4 seconds, we pause playback.  ("Continuous" means at least 1 keystroke per second).
  * If the user stops after that, we restart playback and seek back 3 seconds.  ("stops" means no keystrokes for an entire second).

**Dean says:**

At the suggestion of Maggie (aka PCF Testing), I agree it would be best to include three playback modes, as follows:
* Beginner: Play 4 seconds then pause.
* Magic: Automatically pauses and restarts.
* Expert: Use your tab key to play/pause.

**UI Suggestion:**

![image](https://cloud.githubusercontent.com/assets/299270/2660176/994bc7e6-c01c-11e3-99ea-5ee0f20d800d.png)

Clicking on the playback mode would open a modal that would show the 3 playback modes (and brief descriptions) and enable an user to select one. The default would be "Magic".

**Janet notes:**

We don't want to do any auto-pausing when the user it trying to sync or review subtitles, it's too disruptive. Really this should only be for the typing stage – it could automatically switch to expert mode when an user toggles from stage 1 to stage 2. (Dean: Sometimes users do end up doing transcription in stage 2, so it'd be nice if they could still toggle the setting).

**Comment by nslottow** [comment]
Ben asked me to do a write-up of the work I've done so far in my branch, and explain where someone could pick up the code:

My changes can be viewed and tested by checking out this branch: https://github.com/nslottow/unisubs/tree/gh-784-nslottow
Make sure to run `bin/dev migrate` or at least `bin/dev migrate auth` because my changes add a user preference field to remember the last selected playback mode.

I implemented the 3 different playback modes: Beginner (play for 4 seconds then stop), Standard (no auto-pausing), and Magic (pause after 4 seconds of continuous typing, then after 1 second of no keystrokes, resume from 3 seconds ago).  Most of the functionality is in the PlaybackModeController in `media/src/js/subtitle-editor/video/controllers.js`.

The magic pause mode handler is the most involved, and is implemented as a simple state machine that works like this:

1. When the user makes a subtitle editing keystroke, it starts two timers:
    * The first timer is for 1 second, and if it completes without the user making another keystroke to restart the timer, it resets the state machine
    * The second timer is for 4 seconds, and if it completes without the state machine being reset by the first timer, it checks if the video player is in the state that we expect (still playing and at a timecode 4 seconds from when we started the timer), then it begins the magic pause.
2. When magically paused, it starts one timer for one second
    * If the timer completes without the user making another keystroke to restart the timer, the video is magically resumed and seeked backwards 3 seconds
3. If at any point during this process the video player is put into a state that the magic pause state machine does not expect (e.g. it is seeked or paused before the magic pause timer completes), the state machine will reset, meaning it will not touch the video player again until it is restarted from a valid state (i.e. the video is playing, and the user starts editing subtitles).

I did not get around to automatically switching the playback mode when the user switches subtitling steps. I have a question about that though: while it may be useful to have it switch automatically, would it be more preferable to have two different user preference values, one for the playback mode during step 1 and one for the playback mode during steps 2 and 3?

Another question I had was: the timeout values Ben described seem to work well for subtitling English as a native speaker, but that might not be the case for other languages.  It might be worth adding user settings to control the timeouts and how far the video skips back upon resuming.

So to finish this feature, this is how I see the work left to do:
* Implement UI as a hover menu (right now it is a modal dialog) and/or work with designers to come up with a better solution that incorporates all the relevant user settings.
* Potentially add a user setting for what the default playback mode for steps 2 & 3 of subtitling is, and automatically switch the playback mode when the user switches between subtitling steps.
* Potentially add user settings for controlling the timeouts used for magic pause mode
* User testing with all different video types (I mainly tested with YouTube, and as I've been writing this up Vimeo)
* Unit tests
* Remove debug logging from the PlaybackModeController

**Comment by PCF-Testing** [comment]
This seems to work according to the spec on the major video formats supported by Amara (YT, Vimeo, MP4, OGV, Brightcove, Kaltura), with the tiny exception that on BC videos autopause feature sometimes gets stuck and would not resume automatically. Since BC videos are relatively rare and pressing TAB key always resumes the video, this seems to be a minor issue that can be dealt with later.

I don't think we should try and guess the best possible pace for transcribers. Instead, I suggest that we roll out the autopause feature as is and listen to the feedback from expert-level and beginning caption makers, and adjust the pace based on their input.

Right now we should focus on ironing out the UI and deciding on the default settings.

Modal dialog UI:
- [ ] The drop-down selector is way too short, it should accommodate the full length of the text, and ideally span most of the dialog width to allow translation into other languages (which may be less compact than English)
![playbackmode](https://cloud.githubusercontent.com/assets/288455/18087077/18aa469c-6e68-11e6-85a3-fac4071b9871.png)
- [ ] Dialog title: I suggest titling it "Video Playback and Pause Preferences". Other wording suggestions are welcome.
- [ ] Button: how about making it read "Apply" rather than "Close"?

Regarding the default settings, we should choose them wisely to make users aware about the new option. If it is not too complicated technically, then I'd suggest the following approach:
- For all new users, set the playback mode to Beginner until they make their own choice
- For existing users:
* If they have Show Tutorial on, set the playback mode to Beginner
* Otherwise, set it to Recommended
If this is too complicated, then let's make it simple and set the playback mode to Beginner for everyone and permit users to experiment and make their choice.

There was also a good suggestion to add the playback mode option to the tutorial, but that could wait until the next round of improvements.

Thoughts?

**Comment by PCF-Testing** [comment]
@nslottow: after discussing the proposed changes we decided on the following:

1) Make the UI changes described in the previous comment
2) Leave the default setting to Standard (no pause) mode for all users, new and existing ones. After the feature has been around for a while, we can reconsider that again
3) Wait for the users' feedback and adjust the pace based on that. No changes in pause/playback pattern for now.

**Comment by nslottow** [comment]
@PCF-Testing Thanks for the feedback.  I got the go ahead from Dean to continue working on this so I'll make the changes you suggested, see if I can add some unit tests if they make sense, and then prepare a pull request.

One question about the current functionality: Should the auto-pause feature magically rewind & resume the video if they start it from 3-4 seconds before the end, and start typing, and the video ends?

**Comment by PCF-Testing** [comment]
@nslottow: if the magical autopause happened 3-4 sec before the end of the video, I think the editor should skip 3 sec back, as usual, play the video till the end and stop. 

Your comment regarding "Close" button is correct, "Apply" does not make sense if the playback mode is switched the moment another value is selected from the drop-down list. Let us keep the current button caption ("Close") and behaviour, changing the behaviour of the button would be too invasive - I don't think it is really worth all the pain.

**Comment by deanjansen** [comment]
@PCF-Testing Do you know if this should be available on staging? (or if it will happen on the next staging deploy?)

**Comment by nslottow** [comment]
I haven't created a pull request for this yet.  I spent some time
investigating whether we could make the auto-rewind/resume functionality
work at the end of videos as Maggie and I discussed.  It seems to conflict
with how popcorn.js sets the state of the video player.  So I decided to
forgo that change.

I was planning on finishing the unit tests and preparing a pull request
yesterday afternoon, but I got my laptop stolen after Dean and I talked :(

I have some time tomorrow and Wednesday evening to get my dev environment
setup again and prepare that PR.

Optionally we could merge in my changes minus the unit tests.

**Comment by PCF-Testing** [comment]
@nslottow: https://github.com/nslottow/unisubs/tree/gh-784-nslottow seems to be way behind unisubs/staging, which makes it non-testable. Could you please merge in the latest changes from staging? If you have any questions regarding this, @bendk could help. Thank you!

**Comment by nslottow** [comment]
Yep that's no problem. I can merge in the latest changes from staging later
tonight.

**Comment by PCF-Testing** [comment]
The drop-down width in the dialog has not been fixed - the text still does not fit. The width of select.ng-pristine.ng-valid should be equal to the width of h3#playback-mode-heading. Currently, it spans less than half of this width.

**Comment by PCF-Testing** [comment]
Also, the number for add_field_userlanguage_priority migration needs to be changed - auth 0039 is already taken by another migration (add_field_customuser_allow_3rd_party_login).

**Comment by nslottow** [comment]
Ah thanks for checking on this. The drop down width was a change I did on
the laptop that got stolen.  Good to know about the migration number.  Will
fix both.

**Comment by nslottow** [comment]
@PCF-Testing I've fixed the migration number and the width of the drop-down selector and pushed the changes to my pull request #2657

**Comment by PCF-Testing** [comment]
Looks good now. Marking as Waiting for Deploy.

**Comment by PCF-Testing** [comment]
I'll close this one when it goes live and the release notes get posted.

**Comment by PCF-Testing** [comment]
Deployed.
